using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using EnvironmentManager.Models;
using EnvironmentManager.Data; // Assuming DbContext is here
using System.Collections.ObjectModel;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore; // Required for ToListAsync etc.
using System.Linq; // Required for LINQ queries like OrderBy

namespace EnvironmentManager.ViewModels
{
    public partial class SensorViewModel : ObservableObject
    {
        private readonly MaintenanceDbContext _context;

        [ObservableProperty]
        private ObservableCollection<Sensor> _sensors;

        [ObservableProperty]
        private Sensor? _selectedSensor; // For editing/details view - Made nullable

        [ObservableProperty]
        private string _sensorName;
        [ObservableProperty]
        private string _model;
        [ObservableProperty]
        private string _manufacturer;
        [ObservableProperty]
        private string _sensorType;
        [ObservableProperty]
        private DateTime _installationDate = DateTime.Now; // Default to today
        [ObservableProperty]
        private bool _isActive = true; // Default to active
        [ObservableProperty]
        private DateTime? _lastCalibration;
        [ObservableProperty]
        private string _firmwareVersion;
        [ObservableProperty]
        private string _dataSource;
        [ObservableProperty]
        private string _sensorUrl;
        [ObservableProperty]
        private DateTime? _lastHeartbeat;
        [ObservableProperty]
        private string _connectivityStatus;
        [ObservableProperty]
        private float? _batteryLevelPercentage;
        [ObservableProperty]
        private int? _signalStrengthDbm;

        [ObservableProperty] // Restore this attribute
        private bool _isEditing = false;

        [ObservableProperty]
        private string _pageTitle = "Add New Sensor"; // Initialize title

        public SensorViewModel(MaintenanceDbContext context)
        {
            _context = context;
            _sensors = new ObservableCollection<Sensor>();
            // Load initial data when the ViewModel is created
            UpdatePageTitle(); // Set initial title based on IsEditing state
            LoadSensorsCommand.ExecuteAsync(null);
        }

        // This method is auto-generated by CommunityToolkit.Mvvm when IsEditing changes
        partial void OnIsEditingChanged(bool value)
        {
            UpdatePageTitle(); // Update the title whenever IsEditing changes
        }

        private void UpdatePageTitle()
        {
            PageTitle = IsEditing ? "Edit Sensor" : "Add New Sensor";
        }

        [RelayCommand]
        private async Task LoadSensorsAsync()
        {
            Sensors.Clear();
            var sensorsList = await _context.Sensors.OrderBy(s => s.SensorName).ToListAsync();
            foreach (var sensor in sensorsList)
            {
                Sensors.Add(sensor);
            }
        }

        [RelayCommand]
        private void PrepareNewSensor()
        {
            SelectedSensor = null; // Clear any selection
            IsEditing = false; // Set mode to Adding (this will trigger OnIsEditingChanged via partial method)

            // Reset form fields
            SensorName = string.Empty;
            Model = string.Empty;
            Manufacturer = string.Empty;
            SensorType = string.Empty;
            InstallationDate = DateTime.Now;
            IsActive = true;
            LastCalibration = null;
            FirmwareVersion = string.Empty;
            DataSource = string.Empty;
            SensorUrl = string.Empty;
            LastHeartbeat = null;
            ConnectivityStatus = string.Empty;
            BatteryLevelPercentage = null;
            SignalStrengthDbm = null;

            // Potentially navigate to an Add/Edit sub-page or change UI state
            // For now, we assume the same page handles add/edit
        }

        [RelayCommand]
        private void SelectSensorForEdit(Sensor? sensor) // Parameter can be null now
        {
            if (sensor == null) return;

            SelectedSensor = sensor;
            IsEditing = true; // Set mode to Editing (this will trigger OnIsEditingChanged via partial method)

            // Load selected sensor data into form fields
            SensorName = sensor.SensorName;
            Model = sensor.Model;
            Manufacturer = sensor.Manufacturer;
            SensorType = sensor.SensorType;
            InstallationDate = sensor.InstallationDate;
            IsActive = sensor.IsActive;
            LastCalibration = sensor.LastCalibration;
            FirmwareVersion = sensor.FirmwareVersion;
            DataSource = sensor.DataSource;
            SensorUrl = sensor.SensorUrl;
            LastHeartbeat = sensor.LastHeartbeat;
            ConnectivityStatus = sensor.ConnectivityStatus;
            BatteryLevelPercentage = sensor.BatteryLevelPercentage;
            SignalStrengthDbm = sensor.SignalStrengthDbm;

            // Potentially navigate or change UI state
        }


        [RelayCommand]
        private async Task SaveSensorAsync()
        {
            if (string.IsNullOrWhiteSpace(SensorName))
            {
                // Basic validation
                await Shell.Current.DisplayAlert("Error", "Sensor Name is required.", "OK");
                return;
            }

            Sensor sensorToSave;

            if (IsEditing && SelectedSensor != null)
            {
                // Update existing sensor
                sensorToSave = SelectedSensor;
            }
            else
            {
                // Create new sensor
                sensorToSave = new Sensor();
                _context.Sensors.Add(sensorToSave); // Add to context for tracking
            }

            // Map form fields back to the sensor object
            sensorToSave.SensorName = SensorName;
            sensorToSave.Model = Model;
            sensorToSave.Manufacturer = Manufacturer;
            sensorToSave.SensorType = SensorType;
            sensorToSave.InstallationDate = InstallationDate;
            sensorToSave.IsActive = IsActive;
            sensorToSave.LastCalibration = LastCalibration;
            sensorToSave.FirmwareVersion = FirmwareVersion;
            sensorToSave.DataSource = DataSource;
            sensorToSave.SensorUrl = SensorUrl;
            sensorToSave.LastHeartbeat = LastHeartbeat;
            sensorToSave.ConnectivityStatus = ConnectivityStatus;
            sensorToSave.BatteryLevelPercentage = BatteryLevelPercentage;
            sensorToSave.SignalStrengthDbm = SignalStrengthDbm;

            try
            {
                await _context.SaveChangesAsync();

                // Reset state and reload list
                PrepareNewSensor(); // Reset form
                await LoadSensorsAsync(); // Refresh the list
                await Shell.Current.DisplayAlert("Success", "Sensor saved successfully.", "OK");
            }
            catch (Exception ex)
            {
                await Shell.Current.DisplayAlert("Error", $"Failed to save sensor: {ex.Message}", "OK");
                // Optionally detach the entity if saving failed during add
                if (!IsEditing)
                {
                    _context.Entry(sensorToSave).State = EntityState.Detached;
                }
            }
        }

        [RelayCommand]
        private async Task DeleteSensorAsync(Sensor? sensor) // Parameter can be null
        {
            if (sensor == null) return;

            bool confirm = await Shell.Current.DisplayAlert("Confirm Delete", $"Are you sure you want to delete sensor '{sensor.SensorName}'?", "Yes", "No");
            if (!confirm) return;

            try
            {
                _context.Sensors.Remove(sensor);
                await _context.SaveChangesAsync();

                // If the deleted sensor was being edited, reset the form
                if (SelectedSensor == sensor)
                {
                    PrepareNewSensor();
                }
                await LoadSensorsAsync(); // Refresh the list
                await Shell.Current.DisplayAlert("Success", "Sensor deleted successfully.", "OK");
            }
            catch (Exception ex)
            {
                await Shell.Current.DisplayAlert("Error", $"Failed to delete sensor: {ex.Message}", "OK");
                // Re-attach the entity if needed, or handle context state
                 _context.Entry(sensor).State = EntityState.Unchanged; // Or reload context
            }
        }
    }
}
