### YamlMime:ManagedReference
items:
- uid: EnvironmentManager.ViewModels
  commentId: N:EnvironmentManager.ViewModels
  id: EnvironmentManager.ViewModels
  children:
  - EnvironmentManager.ViewModels.AboutViewModel
  - EnvironmentManager.ViewModels.AddSensorViewModel
  - EnvironmentManager.ViewModels.AddUserViewModel
  - EnvironmentManager.ViewModels.AdminLocationViewModel
  - EnvironmentManager.ViewModels.AdminUserViewModel
  - EnvironmentManager.ViewModels.AirQualityAdminViewModel
  - EnvironmentManager.ViewModels.AlertViewModel
  - EnvironmentManager.ViewModels.AllMaintenanceViewModel
  - EnvironmentManager.ViewModels.ArchiveAirQualityViewModel
  - EnvironmentManager.ViewModels.BaseViewModel
  - EnvironmentManager.ViewModels.DatabaseAdminViewModel
  - EnvironmentManager.ViewModels.EditAirQualityViewModel
  - EnvironmentManager.ViewModels.EditArchiveAirQualityViewModel
  - EnvironmentManager.ViewModels.EditLocationViewModel
  - EnvironmentManager.ViewModels.EditSensorViewModel
  - EnvironmentManager.ViewModels.EditUserViewModel
  - EnvironmentManager.ViewModels.ErrorTableAdminViewModel
  - EnvironmentManager.ViewModels.ErrorViewModel
  - EnvironmentManager.ViewModels.HistoricalAirQualityViewModel
  - EnvironmentManager.ViewModels.HistoricalDataSelectionViewModel
  - EnvironmentManager.ViewModels.HistoricalDataViewerViewModel
  - EnvironmentManager.ViewModels.HomeViewModel
  - EnvironmentManager.ViewModels.LogViewModel
  - EnvironmentManager.ViewModels.MaintenanceViewModel
  - EnvironmentManager.ViewModels.ResolvedAlertsViewModel
  - EnvironmentManager.ViewModels.SensorViewModel
  langs:
  - csharp
  - vb
  name: EnvironmentManager.ViewModels
  nameWithType: EnvironmentManager.ViewModels
  fullName: EnvironmentManager.ViewModels
  type: Namespace
  assemblies:
  - EnvironmentManager
references:
- uid: EnvironmentManager.ViewModels.AboutViewModel
  commentId: T:EnvironmentManager.ViewModels.AboutViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.AboutViewModel.html
  name: AboutViewModel
  nameWithType: AboutViewModel
  fullName: EnvironmentManager.ViewModels.AboutViewModel
- uid: EnvironmentManager.ViewModels.AddSensorViewModel
  commentId: T:EnvironmentManager.ViewModels.AddSensorViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.AddSensorViewModel.html
  name: AddSensorViewModel
  nameWithType: AddSensorViewModel
  fullName: EnvironmentManager.ViewModels.AddSensorViewModel
- uid: EnvironmentManager.ViewModels.AddUserViewModel
  commentId: T:EnvironmentManager.ViewModels.AddUserViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.AddUserViewModel.html
  name: AddUserViewModel
  nameWithType: AddUserViewModel
  fullName: EnvironmentManager.ViewModels.AddUserViewModel
- uid: EnvironmentManager.ViewModels.AdminLocationViewModel
  commentId: T:EnvironmentManager.ViewModels.AdminLocationViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.AdminLocationViewModel.html
  name: AdminLocationViewModel
  nameWithType: AdminLocationViewModel
  fullName: EnvironmentManager.ViewModels.AdminLocationViewModel
- uid: EnvironmentManager.ViewModels.AdminUserViewModel
  commentId: T:EnvironmentManager.ViewModels.AdminUserViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.AdminUserViewModel.html
  name: AdminUserViewModel
  nameWithType: AdminUserViewModel
  fullName: EnvironmentManager.ViewModels.AdminUserViewModel
- uid: EnvironmentManager.ViewModels.AirQualityAdminViewModel
  commentId: T:EnvironmentManager.ViewModels.AirQualityAdminViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.AirQualityAdminViewModel.html
  name: AirQualityAdminViewModel
  nameWithType: AirQualityAdminViewModel
  fullName: EnvironmentManager.ViewModels.AirQualityAdminViewModel
- uid: EnvironmentManager.ViewModels.AlertViewModel
  commentId: T:EnvironmentManager.ViewModels.AlertViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.AlertViewModel.html
  name: AlertViewModel
  nameWithType: AlertViewModel
  fullName: EnvironmentManager.ViewModels.AlertViewModel
- uid: EnvironmentManager.ViewModels.AllMaintenanceViewModel
  commentId: T:EnvironmentManager.ViewModels.AllMaintenanceViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.AllMaintenanceViewModel.html
  name: AllMaintenanceViewModel
  nameWithType: AllMaintenanceViewModel
  fullName: EnvironmentManager.ViewModels.AllMaintenanceViewModel
- uid: EnvironmentManager.ViewModels.ArchiveAirQualityViewModel
  commentId: T:EnvironmentManager.ViewModels.ArchiveAirQualityViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.ArchiveAirQualityViewModel.html
  name: ArchiveAirQualityViewModel
  nameWithType: ArchiveAirQualityViewModel
  fullName: EnvironmentManager.ViewModels.ArchiveAirQualityViewModel
- uid: EnvironmentManager.ViewModels.BaseViewModel
  commentId: T:EnvironmentManager.ViewModels.BaseViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.BaseViewModel.html
  name: BaseViewModel
  nameWithType: BaseViewModel
  fullName: EnvironmentManager.ViewModels.BaseViewModel
- uid: EnvironmentManager.ViewModels.DatabaseAdminViewModel
  commentId: T:EnvironmentManager.ViewModels.DatabaseAdminViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.DatabaseAdminViewModel.html
  name: DatabaseAdminViewModel
  nameWithType: DatabaseAdminViewModel
  fullName: EnvironmentManager.ViewModels.DatabaseAdminViewModel
- uid: EnvironmentManager.ViewModels.EditAirQualityViewModel
  commentId: T:EnvironmentManager.ViewModels.EditAirQualityViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.EditAirQualityViewModel.html
  name: EditAirQualityViewModel
  nameWithType: EditAirQualityViewModel
  fullName: EnvironmentManager.ViewModels.EditAirQualityViewModel
- uid: EnvironmentManager.ViewModels.EditArchiveAirQualityViewModel
  commentId: T:EnvironmentManager.ViewModels.EditArchiveAirQualityViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.EditArchiveAirQualityViewModel.html
  name: EditArchiveAirQualityViewModel
  nameWithType: EditArchiveAirQualityViewModel
  fullName: EnvironmentManager.ViewModels.EditArchiveAirQualityViewModel
- uid: EnvironmentManager.ViewModels.EditLocationViewModel
  commentId: T:EnvironmentManager.ViewModels.EditLocationViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.EditLocationViewModel.html
  name: EditLocationViewModel
  nameWithType: EditLocationViewModel
  fullName: EnvironmentManager.ViewModels.EditLocationViewModel
- uid: EnvironmentManager.ViewModels.EditSensorViewModel
  commentId: T:EnvironmentManager.ViewModels.EditSensorViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.EditSensorViewModel.html
  name: EditSensorViewModel
  nameWithType: EditSensorViewModel
  fullName: EnvironmentManager.ViewModels.EditSensorViewModel
- uid: EnvironmentManager.ViewModels.EditUserViewModel
  commentId: T:EnvironmentManager.ViewModels.EditUserViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.EditUserViewModel.html
  name: EditUserViewModel
  nameWithType: EditUserViewModel
  fullName: EnvironmentManager.ViewModels.EditUserViewModel
- uid: EnvironmentManager.ViewModels.ErrorTableAdminViewModel
  commentId: T:EnvironmentManager.ViewModels.ErrorTableAdminViewModel
  href: EnvironmentManager.ViewModels.ErrorTableAdminViewModel.html
  name: ErrorTableAdminViewModel
  nameWithType: ErrorTableAdminViewModel
  fullName: EnvironmentManager.ViewModels.ErrorTableAdminViewModel
- uid: EnvironmentManager.ViewModels.ErrorViewModel
  commentId: T:EnvironmentManager.ViewModels.ErrorViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.ErrorViewModel.html
  name: ErrorViewModel
  nameWithType: ErrorViewModel
  fullName: EnvironmentManager.ViewModels.ErrorViewModel
- uid: EnvironmentManager.ViewModels.HistoricalAirQualityViewModel
  commentId: T:EnvironmentManager.ViewModels.HistoricalAirQualityViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.HistoricalAirQualityViewModel.html
  name: HistoricalAirQualityViewModel
  nameWithType: HistoricalAirQualityViewModel
  fullName: EnvironmentManager.ViewModels.HistoricalAirQualityViewModel
- uid: EnvironmentManager.ViewModels.HistoricalDataSelectionViewModel
  commentId: T:EnvironmentManager.ViewModels.HistoricalDataSelectionViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.HistoricalDataSelectionViewModel.html
  name: HistoricalDataSelectionViewModel
  nameWithType: HistoricalDataSelectionViewModel
  fullName: EnvironmentManager.ViewModels.HistoricalDataSelectionViewModel
- uid: EnvironmentManager.ViewModels.HistoricalDataViewerViewModel
  commentId: T:EnvironmentManager.ViewModels.HistoricalDataViewerViewModel
  href: EnvironmentManager.ViewModels.HistoricalDataViewerViewModel.html
  name: HistoricalDataViewerViewModel
  nameWithType: HistoricalDataViewerViewModel
  fullName: EnvironmentManager.ViewModels.HistoricalDataViewerViewModel
- uid: EnvironmentManager.ViewModels.HomeViewModel
  commentId: T:EnvironmentManager.ViewModels.HomeViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.HomeViewModel.html
  name: HomeViewModel
  nameWithType: HomeViewModel
  fullName: EnvironmentManager.ViewModels.HomeViewModel
- uid: EnvironmentManager.ViewModels.LogViewModel
  commentId: T:EnvironmentManager.ViewModels.LogViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.LogViewModel.html
  name: LogViewModel
  nameWithType: LogViewModel
  fullName: EnvironmentManager.ViewModels.LogViewModel
- uid: EnvironmentManager.ViewModels.MaintenanceViewModel
  commentId: T:EnvironmentManager.ViewModels.MaintenanceViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.MaintenanceViewModel.html
  name: MaintenanceViewModel
  nameWithType: MaintenanceViewModel
  fullName: EnvironmentManager.ViewModels.MaintenanceViewModel
- uid: EnvironmentManager.ViewModels.ResolvedAlertsViewModel
  commentId: T:EnvironmentManager.ViewModels.ResolvedAlertsViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.ResolvedAlertsViewModel.html
  name: ResolvedAlertsViewModel
  nameWithType: ResolvedAlertsViewModel
  fullName: EnvironmentManager.ViewModels.ResolvedAlertsViewModel
- uid: EnvironmentManager.ViewModels.SensorViewModel
  commentId: T:EnvironmentManager.ViewModels.SensorViewModel
  parent: EnvironmentManager.ViewModels
  href: EnvironmentManager.ViewModels.SensorViewModel.html
  name: SensorViewModel
  nameWithType: SensorViewModel
  fullName: EnvironmentManager.ViewModels.SensorViewModel
- uid: EnvironmentManager.ViewModels
  commentId: N:EnvironmentManager.ViewModels
  href: EnvironmentManager.html
  name: EnvironmentManager.ViewModels
  nameWithType: EnvironmentManager.ViewModels
  fullName: EnvironmentManager.ViewModels
  spec.csharp:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.ViewModels
    name: ViewModels
    href: EnvironmentManager.ViewModels.html
  spec.vb:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.ViewModels
    name: ViewModels
    href: EnvironmentManager.ViewModels.html
