### YamlMime:ManagedReference
items:
- uid: EnvironmentManager.Data.TableMetadataService
  commentId: T:EnvironmentManager.Data.TableMetadataService
  id: TableMetadataService
  parent: EnvironmentManager.Data
  children:
  - EnvironmentManager.Data.TableMetadataService.TableHasIdColumn(System.String)
  - EnvironmentManager.Data.TableMetadataService.TryGetDateColumn(System.String,System.String@)
  langs:
  - csharp
  - vb
  name: TableMetadataService
  nameWithType: TableMetadataService
  fullName: EnvironmentManager.Data.TableMetadataService
  type: Class
  source:
    remote:
      path: EnvironmentManager/Data/TableMetadataService.cs
      branch: Feature-10
      repo: https://github.com/40626785/Environment-Manager.git
    id: TableMetadataService
    path: ../Data/TableMetadataService.cs
    startLine: 4
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Data
  syntax:
    content: public class TableMetadataService
    content.vb: Public Class TableMetadataService
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: EnvironmentManager.Data.TableMetadataService.TryGetDateColumn(System.String,System.String@)
  commentId: M:EnvironmentManager.Data.TableMetadataService.TryGetDateColumn(System.String,System.String@)
  id: TryGetDateColumn(System.String,System.String@)
  parent: EnvironmentManager.Data.TableMetadataService
  langs:
  - csharp
  - vb
  name: TryGetDateColumn(string, out string)
  nameWithType: TableMetadataService.TryGetDateColumn(string, out string)
  fullName: EnvironmentManager.Data.TableMetadataService.TryGetDateColumn(string, out string)
  type: Method
  source:
    remote:
      path: EnvironmentManager/Data/TableMetadataService.cs
      branch: Feature-10
      repo: https://github.com/40626785/Environment-Manager.git
    id: TryGetDateColumn
    path: ../Data/TableMetadataService.cs
    startLine: 17
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Data
  syntax:
    content: public bool TryGetDateColumn(string tableName, out string columnName)
    parameters:
    - id: tableName
      type: System.String
    - id: columnName
      type: System.String
    return:
      type: System.Boolean
    content.vb: Public Function TryGetDateColumn(tableName As String, columnName As String) As Boolean
  overload: EnvironmentManager.Data.TableMetadataService.TryGetDateColumn*
  nameWithType.vb: TableMetadataService.TryGetDateColumn(String, String)
  fullName.vb: EnvironmentManager.Data.TableMetadataService.TryGetDateColumn(String, String)
  name.vb: TryGetDateColumn(String, String)
- uid: EnvironmentManager.Data.TableMetadataService.TableHasIdColumn(System.String)
  commentId: M:EnvironmentManager.Data.TableMetadataService.TableHasIdColumn(System.String)
  id: TableHasIdColumn(System.String)
  parent: EnvironmentManager.Data.TableMetadataService
  langs:
  - csharp
  - vb
  name: TableHasIdColumn(string)
  nameWithType: TableMetadataService.TableHasIdColumn(string)
  fullName: EnvironmentManager.Data.TableMetadataService.TableHasIdColumn(string)
  type: Method
  source:
    remote:
      path: EnvironmentManager/Data/TableMetadataService.cs
      branch: Feature-10
      repo: https://github.com/40626785/Environment-Manager.git
    id: TableHasIdColumn
    path: ../Data/TableMetadataService.cs
    startLine: 22
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Data
  syntax:
    content: public bool TableHasIdColumn(string tableName)
    parameters:
    - id: tableName
      type: System.String
    return:
      type: System.Boolean
    content.vb: Public Function TableHasIdColumn(tableName As String) As Boolean
  overload: EnvironmentManager.Data.TableMetadataService.TableHasIdColumn*
  nameWithType.vb: TableMetadataService.TableHasIdColumn(String)
  fullName.vb: EnvironmentManager.Data.TableMetadataService.TableHasIdColumn(String)
  name.vb: TableHasIdColumn(String)
references:
- uid: EnvironmentManager.Data
  commentId: N:EnvironmentManager.Data
  href: EnvironmentManager.html
  name: EnvironmentManager.Data
  nameWithType: EnvironmentManager.Data
  fullName: EnvironmentManager.Data
  spec.csharp:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Data
    name: Data
    href: EnvironmentManager.Data.html
  spec.vb:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Data
    name: Data
    href: EnvironmentManager.Data.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: EnvironmentManager.Data.TableMetadataService.TryGetDateColumn*
  commentId: Overload:EnvironmentManager.Data.TableMetadataService.TryGetDateColumn
  href: EnvironmentManager.Data.TableMetadataService.html#EnvironmentManager_Data_TableMetadataService_TryGetDateColumn_System_String_System_String__
  name: TryGetDateColumn
  nameWithType: TableMetadataService.TryGetDateColumn
  fullName: EnvironmentManager.Data.TableMetadataService.TryGetDateColumn
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: EnvironmentManager.Data.TableMetadataService.TableHasIdColumn*
  commentId: Overload:EnvironmentManager.Data.TableMetadataService.TableHasIdColumn
  href: EnvironmentManager.Data.TableMetadataService.html#EnvironmentManager_Data_TableMetadataService_TableHasIdColumn_System_String_
  name: TableHasIdColumn
  nameWithType: TableMetadataService.TableHasIdColumn
  fullName: EnvironmentManager.Data.TableMetadataService.TableHasIdColumn
