### YamlMime:ManagedReference
items:
- uid: EnvironmentManager.Views
  commentId: N:EnvironmentManager.Views
  id: EnvironmentManager.Views
  children:
  - EnvironmentManager.Views.AboutPage
  - EnvironmentManager.Views.AddSensorPage
  - EnvironmentManager.Views.AddUserPage
  - EnvironmentManager.Views.AdminLocationPage
  - EnvironmentManager.Views.AdminUserPage
  - EnvironmentManager.Views.AirQualityPage
  - EnvironmentManager.Views.AlertPage
  - EnvironmentManager.Views.AllMaintenancePage
  - EnvironmentManager.Views.ArchiveAirQualityPage
  - EnvironmentManager.Views.ArchiveWaterQualityPage
  - EnvironmentManager.Views.DatabaseAdminPage
  - EnvironmentManager.Views.EditAirQualityPage
  - EnvironmentManager.Views.EditArchiveAirQualityPage
  - EnvironmentManager.Views.EditLocationPage
  - EnvironmentManager.Views.EditSensorPage
  - EnvironmentManager.Views.EditUserPage
  - EnvironmentManager.Views.ErrorPage
  - EnvironmentManager.Views.HistoricalAirQualityPage
  - EnvironmentManager.Views.HistoricalDataPage
  - EnvironmentManager.Views.HistoricalDataViewerPage
  - EnvironmentManager.Views.HomePage
  - EnvironmentManager.Views.LogPage
  - EnvironmentManager.Views.MaintenancePage
  - EnvironmentManager.Views.ResolvedAlertsPage
  - EnvironmentManager.Views.SensorPage
  langs:
  - csharp
  - vb
  name: EnvironmentManager.Views
  nameWithType: EnvironmentManager.Views
  fullName: EnvironmentManager.Views
  type: Namespace
  assemblies:
  - EnvironmentManager
references:
- uid: EnvironmentManager.Views.AboutPage
  commentId: T:EnvironmentManager.Views.AboutPage
  href: EnvironmentManager.Views.AboutPage.html
  name: AboutPage
  nameWithType: AboutPage
  fullName: EnvironmentManager.Views.AboutPage
- uid: EnvironmentManager.Views.AddSensorPage
  commentId: T:EnvironmentManager.Views.AddSensorPage
  href: EnvironmentManager.Views.AddSensorPage.html
  name: AddSensorPage
  nameWithType: AddSensorPage
  fullName: EnvironmentManager.Views.AddSensorPage
- uid: EnvironmentManager.Views.AddUserPage
  commentId: T:EnvironmentManager.Views.AddUserPage
  href: EnvironmentManager.Views.AddUserPage.html
  name: AddUserPage
  nameWithType: AddUserPage
  fullName: EnvironmentManager.Views.AddUserPage
- uid: EnvironmentManager.Views.AdminLocationPage
  commentId: T:EnvironmentManager.Views.AdminLocationPage
  href: EnvironmentManager.Views.AdminLocationPage.html
  name: AdminLocationPage
  nameWithType: AdminLocationPage
  fullName: EnvironmentManager.Views.AdminLocationPage
- uid: EnvironmentManager.Views.AdminUserPage
  commentId: T:EnvironmentManager.Views.AdminUserPage
  href: EnvironmentManager.Views.AdminUserPage.html
  name: AdminUserPage
  nameWithType: AdminUserPage
  fullName: EnvironmentManager.Views.AdminUserPage
- uid: EnvironmentManager.Views.AirQualityPage
  commentId: T:EnvironmentManager.Views.AirQualityPage
  href: EnvironmentManager.Views.AirQualityPage.html
  name: AirQualityPage
  nameWithType: AirQualityPage
  fullName: EnvironmentManager.Views.AirQualityPage
- uid: EnvironmentManager.Views.AlertPage
  commentId: T:EnvironmentManager.Views.AlertPage
  href: EnvironmentManager.Views.AlertPage.html
  name: AlertPage
  nameWithType: AlertPage
  fullName: EnvironmentManager.Views.AlertPage
- uid: EnvironmentManager.Views.AllMaintenancePage
  commentId: T:EnvironmentManager.Views.AllMaintenancePage
  href: EnvironmentManager.Views.AllMaintenancePage.html
  name: AllMaintenancePage
  nameWithType: AllMaintenancePage
  fullName: EnvironmentManager.Views.AllMaintenancePage
- uid: EnvironmentManager.Views.ArchiveAirQualityPage
  commentId: T:EnvironmentManager.Views.ArchiveAirQualityPage
  href: EnvironmentManager.Views.ArchiveAirQualityPage.html
  name: ArchiveAirQualityPage
  nameWithType: ArchiveAirQualityPage
  fullName: EnvironmentManager.Views.ArchiveAirQualityPage
- uid: EnvironmentManager.Views.ArchiveWaterQualityPage
  commentId: T:EnvironmentManager.Views.ArchiveWaterQualityPage
  href: EnvironmentManager.Views.ArchiveWaterQualityPage.html
  name: ArchiveWaterQualityPage
  nameWithType: ArchiveWaterQualityPage
  fullName: EnvironmentManager.Views.ArchiveWaterQualityPage
- uid: EnvironmentManager.Views.DatabaseAdminPage
  commentId: T:EnvironmentManager.Views.DatabaseAdminPage
  href: EnvironmentManager.Views.DatabaseAdminPage.html
  name: DatabaseAdminPage
  nameWithType: DatabaseAdminPage
  fullName: EnvironmentManager.Views.DatabaseAdminPage
- uid: EnvironmentManager.Views.EditAirQualityPage
  commentId: T:EnvironmentManager.Views.EditAirQualityPage
  href: EnvironmentManager.Views.EditAirQualityPage.html
  name: EditAirQualityPage
  nameWithType: EditAirQualityPage
  fullName: EnvironmentManager.Views.EditAirQualityPage
- uid: EnvironmentManager.Views.EditArchiveAirQualityPage
  commentId: T:EnvironmentManager.Views.EditArchiveAirQualityPage
  href: EnvironmentManager.Views.EditArchiveAirQualityPage.html
  name: EditArchiveAirQualityPage
  nameWithType: EditArchiveAirQualityPage
  fullName: EnvironmentManager.Views.EditArchiveAirQualityPage
- uid: EnvironmentManager.Views.EditLocationPage
  commentId: T:EnvironmentManager.Views.EditLocationPage
  href: EnvironmentManager.Views.EditLocationPage.html
  name: EditLocationPage
  nameWithType: EditLocationPage
  fullName: EnvironmentManager.Views.EditLocationPage
- uid: EnvironmentManager.Views.EditSensorPage
  commentId: T:EnvironmentManager.Views.EditSensorPage
  href: EnvironmentManager.Views.EditSensorPage.html
  name: EditSensorPage
  nameWithType: EditSensorPage
  fullName: EnvironmentManager.Views.EditSensorPage
- uid: EnvironmentManager.Views.EditUserPage
  commentId: T:EnvironmentManager.Views.EditUserPage
  href: EnvironmentManager.Views.EditUserPage.html
  name: EditUserPage
  nameWithType: EditUserPage
  fullName: EnvironmentManager.Views.EditUserPage
- uid: EnvironmentManager.Views.ErrorPage
  commentId: T:EnvironmentManager.Views.ErrorPage
  href: EnvironmentManager.Views.ErrorPage.html
  name: ErrorPage
  nameWithType: ErrorPage
  fullName: EnvironmentManager.Views.ErrorPage
- uid: EnvironmentManager.Views.HistoricalAirQualityPage
  commentId: T:EnvironmentManager.Views.HistoricalAirQualityPage
  href: EnvironmentManager.Views.HistoricalAirQualityPage.html
  name: HistoricalAirQualityPage
  nameWithType: HistoricalAirQualityPage
  fullName: EnvironmentManager.Views.HistoricalAirQualityPage
- uid: EnvironmentManager.Views.HistoricalDataPage
  commentId: T:EnvironmentManager.Views.HistoricalDataPage
  href: EnvironmentManager.Views.HistoricalDataPage.html
  name: HistoricalDataPage
  nameWithType: HistoricalDataPage
  fullName: EnvironmentManager.Views.HistoricalDataPage
- uid: EnvironmentManager.Views.HistoricalDataViewerPage
  commentId: T:EnvironmentManager.Views.HistoricalDataViewerPage
  href: EnvironmentManager.Views.HistoricalDataViewerPage.html
  name: HistoricalDataViewerPage
  nameWithType: HistoricalDataViewerPage
  fullName: EnvironmentManager.Views.HistoricalDataViewerPage
- uid: EnvironmentManager.Views.HomePage
  commentId: T:EnvironmentManager.Views.HomePage
  href: EnvironmentManager.Views.HomePage.html
  name: HomePage
  nameWithType: HomePage
  fullName: EnvironmentManager.Views.HomePage
- uid: EnvironmentManager.Views.LogPage
  commentId: T:EnvironmentManager.Views.LogPage
  href: EnvironmentManager.Views.LogPage.html
  name: LogPage
  nameWithType: LogPage
  fullName: EnvironmentManager.Views.LogPage
- uid: EnvironmentManager.Views.MaintenancePage
  commentId: T:EnvironmentManager.Views.MaintenancePage
  href: EnvironmentManager.Views.MaintenancePage.html
  name: MaintenancePage
  nameWithType: MaintenancePage
  fullName: EnvironmentManager.Views.MaintenancePage
- uid: EnvironmentManager.Views.ResolvedAlertsPage
  commentId: T:EnvironmentManager.Views.ResolvedAlertsPage
  href: EnvironmentManager.Views.ResolvedAlertsPage.html
  name: ResolvedAlertsPage
  nameWithType: ResolvedAlertsPage
  fullName: EnvironmentManager.Views.ResolvedAlertsPage
- uid: EnvironmentManager.Views.SensorPage
  commentId: T:EnvironmentManager.Views.SensorPage
  href: EnvironmentManager.Views.SensorPage.html
  name: SensorPage
  nameWithType: SensorPage
  fullName: EnvironmentManager.Views.SensorPage
