### YamlMime:ManagedReference
items:
- uid: EnvironmentManager.Models
  commentId: N:EnvironmentManager.Models
  id: EnvironmentManager.Models
  children:
  - EnvironmentManager.Models.EnvironmentalParameter
  - EnvironmentManager.Models.Location
  - EnvironmentManager.Models.Maintenance
  - EnvironmentManager.Models.Sensor
  - EnvironmentManager.Models.SensorReading
  - EnvironmentManager.Models.SensorSetting
  langs:
  - csharp
  - vb
  name: EnvironmentManager.Models
  nameWithType: EnvironmentManager.Models
  fullName: EnvironmentManager.Models
  type: Namespace
  assemblies:
  - EnvironmentManager
references:
- uid: EnvironmentManager.Models.EnvironmentalParameter
  commentId: T:EnvironmentManager.Models.EnvironmentalParameter
  parent: EnvironmentManager.Models
  href: EnvironmentManager.Models.EnvironmentalParameter.html
  name: EnvironmentalParameter
  nameWithType: EnvironmentalParameter
  fullName: EnvironmentManager.Models.EnvironmentalParameter
- uid: EnvironmentManager.Models.Location
  commentId: T:EnvironmentManager.Models.Location
  parent: EnvironmentManager.Models
  href: EnvironmentManager.Models.Location.html
  name: Location
  nameWithType: Location
  fullName: EnvironmentManager.Models.Location
- uid: EnvironmentManager.Models.Maintenance
  commentId: T:EnvironmentManager.Models.Maintenance
  parent: EnvironmentManager.Models
  href: EnvironmentManager.Models.Maintenance.html
  name: Maintenance
  nameWithType: Maintenance
  fullName: EnvironmentManager.Models.Maintenance
- uid: EnvironmentManager.Models.Sensor
  commentId: T:EnvironmentManager.Models.Sensor
  parent: EnvironmentManager.Models
  href: EnvironmentManager.Models.Sensor.html
  name: Sensor
  nameWithType: Sensor
  fullName: EnvironmentManager.Models.Sensor
- uid: EnvironmentManager.Models.SensorReading
  commentId: T:EnvironmentManager.Models.SensorReading
  href: EnvironmentManager.Models.SensorReading.html
  name: SensorReading
  nameWithType: SensorReading
  fullName: EnvironmentManager.Models.SensorReading
- uid: EnvironmentManager.Models.SensorSetting
  commentId: T:EnvironmentManager.Models.SensorSetting
  href: EnvironmentManager.Models.SensorSetting.html
  name: SensorSetting
  nameWithType: SensorSetting
  fullName: EnvironmentManager.Models.SensorSetting
- uid: EnvironmentManager.Models
  commentId: N:EnvironmentManager.Models
  href: EnvironmentManager.html
  name: EnvironmentManager.Models
  nameWithType: EnvironmentManager.Models
  fullName: EnvironmentManager.Models
  spec.csharp:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Models
    name: Models
    href: EnvironmentManager.Models.html
  spec.vb:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Models
    name: Models
    href: EnvironmentManager.Models.html
