### YamlMime:ManagedReference
items:
- uid: EnvironmentManager
  commentId: N:EnvironmentManager
  id: EnvironmentManager
  children:
  - EnvironmentManager.App
  - EnvironmentManager.AppShell
  - EnvironmentManager.MauiProgram
  langs:
  - csharp
  - vb
  name: EnvironmentManager
  nameWithType: EnvironmentManager
  fullName: EnvironmentManager
  type: Namespace
  assemblies:
  - EnvironmentManager
references:
- uid: EnvironmentManager.App
  commentId: T:EnvironmentManager.App
  href: EnvironmentManager.App.html
  name: App
  nameWithType: App
  fullName: EnvironmentManager.App
- uid: EnvironmentManager.AppShell
  commentId: T:EnvironmentManager.AppShell
  href: EnvironmentManager.AppShell.html
  name: AppShell
  nameWithType: AppShell
  fullName: EnvironmentManager.AppShell
- uid: EnvironmentManager.MauiProgram
  commentId: T:EnvironmentManager.MauiProgram
  href: EnvironmentManager.MauiProgram.html
  name: MauiProgram
  nameWithType: MauiProgram
  fullName: EnvironmentManager.MauiProgram
