### YamlMime:ManagedReference
items:
- uid: EnvironmentManager.Interfaces.IErrorHandling
  commentId: T:EnvironmentManager.Interfaces.IErrorHandling
  id: IErrorHandling
  parent: EnvironmentManager.Interfaces
  children:
  - EnvironmentManager.Interfaces.IErrorHandling.DisplayError
  - EnvironmentManager.Interfaces.IErrorHandling.HandleError(System.Exception,System.String)
  langs:
  - csharp
  - vb
  name: IErrorHandling
  nameWithType: IErrorHandling
  fullName: EnvironmentManager.Interfaces.IErrorHandling
  type: Interface
  source:
    remote:
      path: EnvironmentManager/Interfaces/IErrorHandling.cs
      branch: feat/5-threshold-map
      repo: https://github.com/40626785/SEGroup.git
    id: IErrorHandling
    path: EnvironmentManager/Interfaces/IErrorHandling.cs
    startLine: 6
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Interfaces
  summary: Enforces a consistent approach for Error Handling
  example: []
  syntax:
    content: public interface IErrorHandling
    content.vb: Public Interface IErrorHandling
- uid: EnvironmentManager.Interfaces.IErrorHandling.DisplayError
  commentId: P:EnvironmentManager.Interfaces.IErrorHandling.DisplayError
  id: DisplayError
  parent: EnvironmentManager.Interfaces.IErrorHandling
  langs:
  - csharp
  - vb
  name: DisplayError
  nameWithType: IErrorHandling.DisplayError
  fullName: EnvironmentManager.Interfaces.IErrorHandling.DisplayError
  type: Property
  source:
    remote:
      path: EnvironmentManager/Interfaces/IErrorHandling.cs
      branch: feat/5-threshold-map
      repo: https://github.com/40626785/SEGroup.git
    id: DisplayError
    path: EnvironmentManager/Interfaces/IErrorHandling.cs
    startLine: 8
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Interfaces
  syntax:
    content: string DisplayError { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property DisplayError As String
  overload: EnvironmentManager.Interfaces.IErrorHandling.DisplayError*
- uid: EnvironmentManager.Interfaces.IErrorHandling.HandleError(System.Exception,System.String)
  commentId: M:EnvironmentManager.Interfaces.IErrorHandling.HandleError(System.Exception,System.String)
  id: HandleError(System.Exception,System.String)
  parent: EnvironmentManager.Interfaces.IErrorHandling
  langs:
  - csharp
  - vb
  name: HandleError(Exception, string)
  nameWithType: IErrorHandling.HandleError(Exception, string)
  fullName: EnvironmentManager.Interfaces.IErrorHandling.HandleError(System.Exception, string)
  type: Method
  source:
    remote:
      path: EnvironmentManager/Interfaces/IErrorHandling.cs
      branch: feat/5-threshold-map
      repo: https://github.com/40626785/SEGroup.git
    id: HandleError
    path: EnvironmentManager/Interfaces/IErrorHandling.cs
    startLine: 9
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Interfaces
  syntax:
    content: void HandleError(Exception e, string message)
    parameters:
    - id: e
      type: System.Exception
    - id: message
      type: System.String
    content.vb: Sub HandleError(e As Exception, message As String)
  overload: EnvironmentManager.Interfaces.IErrorHandling.HandleError*
  nameWithType.vb: IErrorHandling.HandleError(Exception, String)
  fullName.vb: EnvironmentManager.Interfaces.IErrorHandling.HandleError(System.Exception, String)
  name.vb: HandleError(Exception, String)
references:
- uid: EnvironmentManager.Interfaces
  commentId: N:EnvironmentManager.Interfaces
  href: EnvironmentManager.html
  name: EnvironmentManager.Interfaces
  nameWithType: EnvironmentManager.Interfaces
  fullName: EnvironmentManager.Interfaces
  spec.csharp:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Interfaces
    name: Interfaces
    href: EnvironmentManager.Interfaces.html
  spec.vb:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Interfaces
    name: Interfaces
    href: EnvironmentManager.Interfaces.html
- uid: EnvironmentManager.Interfaces.IErrorHandling.DisplayError*
  commentId: Overload:EnvironmentManager.Interfaces.IErrorHandling.DisplayError
  href: EnvironmentManager.Interfaces.IErrorHandling.html#EnvironmentManager_Interfaces_IErrorHandling_DisplayError
  name: DisplayError
  nameWithType: IErrorHandling.DisplayError
  fullName: EnvironmentManager.Interfaces.IErrorHandling.DisplayError
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: EnvironmentManager.Interfaces.IErrorHandling.HandleError*
  commentId: Overload:EnvironmentManager.Interfaces.IErrorHandling.HandleError
  href: EnvironmentManager.Interfaces.IErrorHandling.html#EnvironmentManager_Interfaces_IErrorHandling_HandleError_System_Exception_System_String_
  name: HandleError
  nameWithType: IErrorHandling.HandleError
  fullName: EnvironmentManager.Interfaces.IErrorHandling.HandleError
- uid: System.Exception
  commentId: T:System.Exception
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.exception
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
