### YamlMime:ManagedReference
items:
- uid: EnvironmentManager.Data
  commentId: N:EnvironmentManager.Data
  id: EnvironmentManager.Data
  children:
  - EnvironmentManager.Data.EnvironmentalParameterDbContext
  - EnvironmentManager.Data.LocationDbContext
  - EnvironmentManager.Data.MaintenanceDbContext
  - EnvironmentManager.Data.SensorDbContext
  langs:
  - csharp
  - vb
  name: EnvironmentManager.Data
  nameWithType: EnvironmentManager.Data
  fullName: EnvironmentManager.Data
  type: Namespace
  assemblies:
  - EnvironmentManager
references:
- uid: EnvironmentManager.Data.EnvironmentalParameterDbContext
  commentId: T:EnvironmentManager.Data.EnvironmentalParameterDbContext
  parent: EnvironmentManager.Data
  href: EnvironmentManager.Data.EnvironmentalParameterDbContext.html
  name: EnvironmentalParameterDbContext
  nameWithType: EnvironmentalParameterDbContext
  fullName: EnvironmentManager.Data.EnvironmentalParameterDbContext
- uid: EnvironmentManager.Data.LocationDbContext
  commentId: T:EnvironmentManager.Data.LocationDbContext
  parent: EnvironmentManager.Data
  href: EnvironmentManager.Data.LocationDbContext.html
  name: LocationDbContext
  nameWithType: LocationDbContext
  fullName: EnvironmentManager.Data.LocationDbContext
- uid: EnvironmentManager.Data.MaintenanceDbContext
  commentId: T:EnvironmentManager.Data.MaintenanceDbContext
  parent: EnvironmentManager.Data
  href: EnvironmentManager.Data.MaintenanceDbContext.html
  name: MaintenanceDbContext
  nameWithType: MaintenanceDbContext
  fullName: EnvironmentManager.Data.MaintenanceDbContext
- uid: EnvironmentManager.Data.SensorDbContext
  commentId: T:EnvironmentManager.Data.SensorDbContext
  parent: EnvironmentManager.Data
  href: EnvironmentManager.Data.SensorDbContext.html
  name: SensorDbContext
  nameWithType: SensorDbContext
  fullName: EnvironmentManager.Data.SensorDbContext
- uid: EnvironmentManager.Data
  commentId: N:EnvironmentManager.Data
  href: EnvironmentManager.html
  name: EnvironmentManager.Data
  nameWithType: EnvironmentManager.Data
  fullName: EnvironmentManager.Data
  spec.csharp:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Data
    name: Data
    href: EnvironmentManager.Data.html
  spec.vb:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Data
    name: Data
    href: EnvironmentManager.Data.html
