### YamlMime:ManagedReference
items:
- uid: EnvironmentManager.Converters
  commentId: N:EnvironmentManager.Converters
  id: EnvironmentManager.Converters
  children:
  - EnvironmentManager.Converters.CountToBoolConverter
  - EnvironmentManager.Converters.NotNullConverter
  - EnvironmentManager.Converters.NotZeroConverter
  - EnvironmentManager.Converters.StatusToColorConverter
  - EnvironmentManager.Converters.StringNotEmptyConverter
  - EnvironmentManager.Converters.StringNotNullOrEmptyConverter
  langs:
  - csharp
  - vb
  name: EnvironmentManager.Converters
  nameWithType: EnvironmentManager.Converters
  fullName: EnvironmentManager.Converters
  type: Namespace
  assemblies:
  - EnvironmentManager
references:
- uid: EnvironmentManager.Converters.CountToBoolConverter
  commentId: T:EnvironmentManager.Converters.CountToBoolConverter
  href: EnvironmentManager.Converters.CountToBoolConverter.html
  name: CountToBoolConverter
  nameWithType: CountToBoolConverter
  fullName: EnvironmentManager.Converters.CountToBoolConverter
- uid: EnvironmentManager.Converters.NotNullConverter
  commentId: T:EnvironmentManager.Converters.NotNullConverter
  href: EnvironmentManager.Converters.NotNullConverter.html
  name: NotNullConverter
  nameWithType: NotNullConverter
  fullName: EnvironmentManager.Converters.NotNullConverter
- uid: EnvironmentManager.Converters.NotZeroConverter
  commentId: T:EnvironmentManager.Converters.NotZeroConverter
  href: EnvironmentManager.Converters.NotZeroConverter.html
  name: NotZeroConverter
  nameWithType: NotZeroConverter
  fullName: EnvironmentManager.Converters.NotZeroConverter
- uid: EnvironmentManager.Converters.StatusToColorConverter
  commentId: T:EnvironmentManager.Converters.StatusToColorConverter
  href: EnvironmentManager.Converters.StatusToColorConverter.html
  name: StatusToColorConverter
  nameWithType: StatusToColorConverter
  fullName: EnvironmentManager.Converters.StatusToColorConverter
- uid: EnvironmentManager.Converters.StringNotEmptyConverter
  commentId: T:EnvironmentManager.Converters.StringNotEmptyConverter
  href: EnvironmentManager.Converters.StringNotEmptyConverter.html
  name: StringNotEmptyConverter
  nameWithType: StringNotEmptyConverter
  fullName: EnvironmentManager.Converters.StringNotEmptyConverter
- uid: EnvironmentManager.Converters.StringNotNullOrEmptyConverter
  commentId: T:EnvironmentManager.Converters.StringNotNullOrEmptyConverter
  href: EnvironmentManager.Converters.StringNotNullOrEmptyConverter.html
  name: StringNotNullOrEmptyConverter
  nameWithType: StringNotNullOrEmptyConverter
  fullName: EnvironmentManager.Converters.StringNotNullOrEmptyConverter
