### YamlMime:ManagedReference
items:
- uid: EnvironmentManager.Services.LoginNavService
  commentId: T:EnvironmentManager.Services.LoginNavService
  id: LoginNavService
  parent: EnvironmentManager.Services
  children:
  - EnvironmentManager.Services.LoginNavService.#ctor(System.IServiceProvider)
  - EnvironmentManager.Services.LoginNavService.RouteOnLogin
  - EnvironmentManager.Services.LoginNavService.RouteOnLogout
  langs:
  - csharp
  - vb
  name: LoginNavService
  nameWithType: LoginNavService
  fullName: EnvironmentManager.Services.LoginNavService
  type: Class
  source:
    remote:
      path: EnvironmentManager/Services/LoginNavService.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: LoginNavService
    path: EnvironmentManager/Services/LoginNavService.cs
    startLine: 10
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Services
  summary: >-
    Allows changing MainPage without handling within ViewModel and breaking MVVM structure.


    Implements ILoginNavService to enable Dependency Injection
  example: []
  syntax:
    content: 'public class LoginNavService : ILoginNavService'
    content.vb: Public Class LoginNavService Implements ILoginNavService
  inheritance:
  - System.Object
  implements:
  - EnvironmentManager.Interfaces.ILoginNavService
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: EnvironmentManager.Services.LoginNavService.#ctor(System.IServiceProvider)
  commentId: M:EnvironmentManager.Services.LoginNavService.#ctor(System.IServiceProvider)
  id: '#ctor(System.IServiceProvider)'
  parent: EnvironmentManager.Services.LoginNavService
  langs:
  - csharp
  - vb
  name: LoginNavService(IServiceProvider)
  nameWithType: LoginNavService.LoginNavService(IServiceProvider)
  fullName: EnvironmentManager.Services.LoginNavService.LoginNavService(System.IServiceProvider)
  type: Constructor
  source:
    remote:
      path: EnvironmentManager/Services/LoginNavService.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: .ctor
    path: EnvironmentManager/Services/LoginNavService.cs
    startLine: 14
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Services
  syntax:
    content: public LoginNavService(IServiceProvider serviceProvider)
    parameters:
    - id: serviceProvider
      type: System.IServiceProvider
    content.vb: Public Sub New(serviceProvider As IServiceProvider)
  overload: EnvironmentManager.Services.LoginNavService.#ctor*
  nameWithType.vb: LoginNavService.New(IServiceProvider)
  fullName.vb: EnvironmentManager.Services.LoginNavService.New(System.IServiceProvider)
  name.vb: New(IServiceProvider)
- uid: EnvironmentManager.Services.LoginNavService.RouteOnLogin
  commentId: M:EnvironmentManager.Services.LoginNavService.RouteOnLogin
  id: RouteOnLogin
  parent: EnvironmentManager.Services.LoginNavService
  langs:
  - csharp
  - vb
  name: RouteOnLogin()
  nameWithType: LoginNavService.RouteOnLogin()
  fullName: EnvironmentManager.Services.LoginNavService.RouteOnLogin()
  type: Method
  source:
    remote:
      path: EnvironmentManager/Services/LoginNavService.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: RouteOnLogin
    path: EnvironmentManager/Services/LoginNavService.cs
    startLine: 22
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Services
  summary: Changes main page to AppShell, granting access to application content
  example: []
  syntax:
    content: public void RouteOnLogin()
    content.vb: Public Sub RouteOnLogin()
  overload: EnvironmentManager.Services.LoginNavService.RouteOnLogin*
  implements:
  - EnvironmentManager.Interfaces.ILoginNavService.RouteOnLogin
- uid: EnvironmentManager.Services.LoginNavService.RouteOnLogout
  commentId: M:EnvironmentManager.Services.LoginNavService.RouteOnLogout
  id: RouteOnLogout
  parent: EnvironmentManager.Services.LoginNavService
  langs:
  - csharp
  - vb
  name: RouteOnLogout()
  nameWithType: LoginNavService.RouteOnLogout()
  fullName: EnvironmentManager.Services.LoginNavService.RouteOnLogout()
  type: Method
  source:
    remote:
      path: EnvironmentManager/Services/LoginNavService.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: RouteOnLogout
    path: EnvironmentManager/Services/LoginNavService.cs
    startLine: 30
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Services
  summary: Changes main page to login, prompting user to reauthenticate
  example: []
  syntax:
    content: public void RouteOnLogout()
    content.vb: Public Sub RouteOnLogout()
  overload: EnvironmentManager.Services.LoginNavService.RouteOnLogout*
  implements:
  - EnvironmentManager.Interfaces.ILoginNavService.RouteOnLogout
references:
- uid: EnvironmentManager.Services
  commentId: N:EnvironmentManager.Services
  href: EnvironmentManager.html
  name: EnvironmentManager.Services
  nameWithType: EnvironmentManager.Services
  fullName: EnvironmentManager.Services
  spec.csharp:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Services
    name: Services
    href: EnvironmentManager.Services.html
  spec.vb:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Services
    name: Services
    href: EnvironmentManager.Services.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: EnvironmentManager.Interfaces.ILoginNavService
  commentId: T:EnvironmentManager.Interfaces.ILoginNavService
  parent: EnvironmentManager.Interfaces
  href: EnvironmentManager.Interfaces.ILoginNavService.html
  name: ILoginNavService
  nameWithType: ILoginNavService
  fullName: EnvironmentManager.Interfaces.ILoginNavService
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: EnvironmentManager.Interfaces
  commentId: N:EnvironmentManager.Interfaces
  href: EnvironmentManager.html
  name: EnvironmentManager.Interfaces
  nameWithType: EnvironmentManager.Interfaces
  fullName: EnvironmentManager.Interfaces
  spec.csharp:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Interfaces
    name: Interfaces
    href: EnvironmentManager.Interfaces.html
  spec.vb:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Interfaces
    name: Interfaces
    href: EnvironmentManager.Interfaces.html
- uid: EnvironmentManager.Services.LoginNavService.#ctor*
  commentId: Overload:EnvironmentManager.Services.LoginNavService.#ctor
  href: EnvironmentManager.Services.LoginNavService.html#EnvironmentManager_Services_LoginNavService__ctor_System_IServiceProvider_
  name: LoginNavService
  nameWithType: LoginNavService.LoginNavService
  fullName: EnvironmentManager.Services.LoginNavService.LoginNavService
  nameWithType.vb: LoginNavService.New
  fullName.vb: EnvironmentManager.Services.LoginNavService.New
  name.vb: New
- uid: System.IServiceProvider
  commentId: T:System.IServiceProvider
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iserviceprovider
  name: IServiceProvider
  nameWithType: IServiceProvider
  fullName: System.IServiceProvider
- uid: EnvironmentManager.Services.LoginNavService.RouteOnLogin*
  commentId: Overload:EnvironmentManager.Services.LoginNavService.RouteOnLogin
  href: EnvironmentManager.Services.LoginNavService.html#EnvironmentManager_Services_LoginNavService_RouteOnLogin
  name: RouteOnLogin
  nameWithType: LoginNavService.RouteOnLogin
  fullName: EnvironmentManager.Services.LoginNavService.RouteOnLogin
- uid: EnvironmentManager.Interfaces.ILoginNavService.RouteOnLogin
  commentId: M:EnvironmentManager.Interfaces.ILoginNavService.RouteOnLogin
  parent: EnvironmentManager.Interfaces.ILoginNavService
  href: EnvironmentManager.Interfaces.ILoginNavService.html#EnvironmentManager_Interfaces_ILoginNavService_RouteOnLogin
  name: RouteOnLogin()
  nameWithType: ILoginNavService.RouteOnLogin()
  fullName: EnvironmentManager.Interfaces.ILoginNavService.RouteOnLogin()
  spec.csharp:
  - uid: EnvironmentManager.Interfaces.ILoginNavService.RouteOnLogin
    name: RouteOnLogin
    href: EnvironmentManager.Interfaces.ILoginNavService.html#EnvironmentManager_Interfaces_ILoginNavService_RouteOnLogin
  - name: (
  - name: )
  spec.vb:
  - uid: EnvironmentManager.Interfaces.ILoginNavService.RouteOnLogin
    name: RouteOnLogin
    href: EnvironmentManager.Interfaces.ILoginNavService.html#EnvironmentManager_Interfaces_ILoginNavService_RouteOnLogin
  - name: (
  - name: )
- uid: EnvironmentManager.Services.LoginNavService.RouteOnLogout*
  commentId: Overload:EnvironmentManager.Services.LoginNavService.RouteOnLogout
  href: EnvironmentManager.Services.LoginNavService.html#EnvironmentManager_Services_LoginNavService_RouteOnLogout
  name: RouteOnLogout
  nameWithType: LoginNavService.RouteOnLogout
  fullName: EnvironmentManager.Services.LoginNavService.RouteOnLogout
- uid: EnvironmentManager.Interfaces.ILoginNavService.RouteOnLogout
  commentId: M:EnvironmentManager.Interfaces.ILoginNavService.RouteOnLogout
  parent: EnvironmentManager.Interfaces.ILoginNavService
  href: EnvironmentManager.Interfaces.ILoginNavService.html#EnvironmentManager_Interfaces_ILoginNavService_RouteOnLogout
  name: RouteOnLogout()
  nameWithType: ILoginNavService.RouteOnLogout()
  fullName: EnvironmentManager.Interfaces.ILoginNavService.RouteOnLogout()
  spec.csharp:
  - uid: EnvironmentManager.Interfaces.ILoginNavService.RouteOnLogout
    name: RouteOnLogout
    href: EnvironmentManager.Interfaces.ILoginNavService.html#EnvironmentManager_Interfaces_ILoginNavService_RouteOnLogout
  - name: (
  - name: )
  spec.vb:
  - uid: EnvironmentManager.Interfaces.ILoginNavService.RouteOnLogout
    name: RouteOnLogout
    href: EnvironmentManager.Interfaces.ILoginNavService.html#EnvironmentManager_Interfaces_ILoginNavService_RouteOnLogout
  - name: (
  - name: )
