### YamlMime:ManagedReference
items:
- uid: EnvironmentManager.Services.LocalStorageService
  commentId: T:EnvironmentManager.Services.LocalStorageService
  id: LocalStorageService
  parent: EnvironmentManager.Services
  children:
  - EnvironmentManager.Services.LocalStorageService.GetStringValue(System.String)
  - EnvironmentManager.Services.LocalStorageService.SetStringValue(System.String,System.String)
  langs:
  - csharp
  - vb
  name: LocalStorageService
  nameWithType: LocalStorageService
  fullName: EnvironmentManager.Services.LocalStorageService
  type: Class
  source:
    remote:
      path: EnvironmentManager/Services/LocalStorageService.cs
      branch: feat/5-threshold-map
      repo: https://github.com/40626785/SEGroup.git
    id: LocalStorageService
    path: EnvironmentManager/Services/LocalStorageService.cs
    startLine: 9
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Services
  summary: >-
    Sets values in Preferences (local storage)


    Implements ILocalStorageService to enable Dependency Injection
  example: []
  syntax:
    content: 'public class LocalStorageService : ILocalStorageService'
    content.vb: Public Class LocalStorageService Implements ILocalStorageService
  inheritance:
  - System.Object
  implements:
  - EnvironmentManager.Interfaces.ILocalStorageService
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: EnvironmentManager.Services.LocalStorageService.SetStringValue(System.String,System.String)
  commentId: M:EnvironmentManager.Services.LocalStorageService.SetStringValue(System.String,System.String)
  id: SetStringValue(System.String,System.String)
  parent: EnvironmentManager.Services.LocalStorageService
  langs:
  - csharp
  - vb
  name: SetStringValue(string, string)
  nameWithType: LocalStorageService.SetStringValue(string, string)
  fullName: EnvironmentManager.Services.LocalStorageService.SetStringValue(string, string)
  type: Method
  source:
    remote:
      path: EnvironmentManager/Services/LocalStorageService.cs
      branch: feat/5-threshold-map
      repo: https://github.com/40626785/SEGroup.git
    id: SetStringValue
    path: EnvironmentManager/Services/LocalStorageService.cs
    startLine: 16
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Services
  summary: Stores string value in Preferences based on provided key and string value
  example: []
  syntax:
    content: public void SetStringValue(string key, string value)
    parameters:
    - id: key
      type: System.String
      description: Name of value, will be used to retrieve value from Preferences
    - id: value
      type: System.String
      description: Value to be set for corresponding key
    content.vb: Public Sub SetStringValue(key As String, value As String)
  overload: EnvironmentManager.Services.LocalStorageService.SetStringValue*
  implements:
  - EnvironmentManager.Interfaces.ILocalStorageService.SetStringValue(System.String,System.String)
  nameWithType.vb: LocalStorageService.SetStringValue(String, String)
  fullName.vb: EnvironmentManager.Services.LocalStorageService.SetStringValue(String, String)
  name.vb: SetStringValue(String, String)
- uid: EnvironmentManager.Services.LocalStorageService.GetStringValue(System.String)
  commentId: M:EnvironmentManager.Services.LocalStorageService.GetStringValue(System.String)
  id: GetStringValue(System.String)
  parent: EnvironmentManager.Services.LocalStorageService
  langs:
  - csharp
  - vb
  name: GetStringValue(string)
  nameWithType: LocalStorageService.GetStringValue(string)
  fullName: EnvironmentManager.Services.LocalStorageService.GetStringValue(string)
  type: Method
  source:
    remote:
      path: EnvironmentManager/Services/LocalStorageService.cs
      branch: feat/5-threshold-map
      repo: https://github.com/40626785/SEGroup.git
    id: GetStringValue
    path: EnvironmentManager/Services/LocalStorageService.cs
    startLine: 26
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Services
  summary: Retrieve string value from Preferences
  example: []
  syntax:
    content: public string GetStringValue(string key)
    parameters:
    - id: key
      type: System.String
      description: ''
    return:
      type: System.String
      description: ''
    content.vb: Public Function GetStringValue(key As String) As String
  overload: EnvironmentManager.Services.LocalStorageService.GetStringValue*
  implements:
  - EnvironmentManager.Interfaces.ILocalStorageService.GetStringValue(System.String)
  nameWithType.vb: LocalStorageService.GetStringValue(String)
  fullName.vb: EnvironmentManager.Services.LocalStorageService.GetStringValue(String)
  name.vb: GetStringValue(String)
references:
- uid: EnvironmentManager.Services
  commentId: N:EnvironmentManager.Services
  href: EnvironmentManager.html
  name: EnvironmentManager.Services
  nameWithType: EnvironmentManager.Services
  fullName: EnvironmentManager.Services
  spec.csharp:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Services
    name: Services
    href: EnvironmentManager.Services.html
  spec.vb:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Services
    name: Services
    href: EnvironmentManager.Services.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: EnvironmentManager.Interfaces.ILocalStorageService
  commentId: T:EnvironmentManager.Interfaces.ILocalStorageService
  parent: EnvironmentManager.Interfaces
  href: EnvironmentManager.Interfaces.ILocalStorageService.html
  name: ILocalStorageService
  nameWithType: ILocalStorageService
  fullName: EnvironmentManager.Interfaces.ILocalStorageService
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: EnvironmentManager.Interfaces
  commentId: N:EnvironmentManager.Interfaces
  href: EnvironmentManager.html
  name: EnvironmentManager.Interfaces
  nameWithType: EnvironmentManager.Interfaces
  fullName: EnvironmentManager.Interfaces
  spec.csharp:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Interfaces
    name: Interfaces
    href: EnvironmentManager.Interfaces.html
  spec.vb:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Interfaces
    name: Interfaces
    href: EnvironmentManager.Interfaces.html
- uid: EnvironmentManager.Services.LocalStorageService.SetStringValue*
  commentId: Overload:EnvironmentManager.Services.LocalStorageService.SetStringValue
  href: EnvironmentManager.Services.LocalStorageService.html#EnvironmentManager_Services_LocalStorageService_SetStringValue_System_String_System_String_
  name: SetStringValue
  nameWithType: LocalStorageService.SetStringValue
  fullName: EnvironmentManager.Services.LocalStorageService.SetStringValue
- uid: EnvironmentManager.Interfaces.ILocalStorageService.SetStringValue(System.String,System.String)
  commentId: M:EnvironmentManager.Interfaces.ILocalStorageService.SetStringValue(System.String,System.String)
  parent: EnvironmentManager.Interfaces.ILocalStorageService
  isExternal: true
  href: EnvironmentManager.Interfaces.ILocalStorageService.html#EnvironmentManager_Interfaces_ILocalStorageService_SetStringValue_System_String_System_String_
  name: SetStringValue(string, string)
  nameWithType: ILocalStorageService.SetStringValue(string, string)
  fullName: EnvironmentManager.Interfaces.ILocalStorageService.SetStringValue(string, string)
  nameWithType.vb: ILocalStorageService.SetStringValue(String, String)
  fullName.vb: EnvironmentManager.Interfaces.ILocalStorageService.SetStringValue(String, String)
  name.vb: SetStringValue(String, String)
  spec.csharp:
  - uid: EnvironmentManager.Interfaces.ILocalStorageService.SetStringValue(System.String,System.String)
    name: SetStringValue
    href: EnvironmentManager.Interfaces.ILocalStorageService.html#EnvironmentManager_Interfaces_ILocalStorageService_SetStringValue_System_String_System_String_
  - name: (
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
  spec.vb:
  - uid: EnvironmentManager.Interfaces.ILocalStorageService.SetStringValue(System.String,System.String)
    name: SetStringValue
    href: EnvironmentManager.Interfaces.ILocalStorageService.html#EnvironmentManager_Interfaces_ILocalStorageService_SetStringValue_System_String_System_String_
  - name: (
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: EnvironmentManager.Services.LocalStorageService.GetStringValue*
  commentId: Overload:EnvironmentManager.Services.LocalStorageService.GetStringValue
  href: EnvironmentManager.Services.LocalStorageService.html#EnvironmentManager_Services_LocalStorageService_GetStringValue_System_String_
  name: GetStringValue
  nameWithType: LocalStorageService.GetStringValue
  fullName: EnvironmentManager.Services.LocalStorageService.GetStringValue
- uid: EnvironmentManager.Interfaces.ILocalStorageService.GetStringValue(System.String)
  commentId: M:EnvironmentManager.Interfaces.ILocalStorageService.GetStringValue(System.String)
  parent: EnvironmentManager.Interfaces.ILocalStorageService
  isExternal: true
  href: EnvironmentManager.Interfaces.ILocalStorageService.html#EnvironmentManager_Interfaces_ILocalStorageService_GetStringValue_System_String_
  name: GetStringValue(string)
  nameWithType: ILocalStorageService.GetStringValue(string)
  fullName: EnvironmentManager.Interfaces.ILocalStorageService.GetStringValue(string)
  nameWithType.vb: ILocalStorageService.GetStringValue(String)
  fullName.vb: EnvironmentManager.Interfaces.ILocalStorageService.GetStringValue(String)
  name.vb: GetStringValue(String)
  spec.csharp:
  - uid: EnvironmentManager.Interfaces.ILocalStorageService.GetStringValue(System.String)
    name: GetStringValue
    href: EnvironmentManager.Interfaces.ILocalStorageService.html#EnvironmentManager_Interfaces_ILocalStorageService_GetStringValue_System_String_
  - name: (
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
  spec.vb:
  - uid: EnvironmentManager.Interfaces.ILocalStorageService.GetStringValue(System.String)
    name: GetStringValue
    href: EnvironmentManager.Interfaces.ILocalStorageService.html#EnvironmentManager_Interfaces_ILocalStorageService_GetStringValue_System_String_
  - name: (
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
