### YamlMime:ManagedReference
items:
- uid: EnvironmentManager.ViewModels.ThresholdMapViewModel
  commentId: T:EnvironmentManager.ViewModels.ThresholdMapViewModel
  id: ThresholdMapViewModel
  parent: EnvironmentManager.ViewModels
  children:
  - EnvironmentManager.ViewModels.ThresholdMapViewModel.#ctor(EnvironmentManager.Interfaces.ISensorDataStore,EnvironmentManager.Interfaces.ISensorThresholdService)
  - EnvironmentManager.ViewModels.ThresholdMapViewModel.GetSensorBreachPins
  langs:
  - csharp
  - vb
  name: ThresholdMapViewModel
  nameWithType: ThresholdMapViewModel
  fullName: EnvironmentManager.ViewModels.ThresholdMapViewModel
  type: Class
  source:
    remote:
      path: EnvironmentManager/ViewModels/ThresholdMapViewModel.cs
      branch: feat/5-threshold-map
      repo: https://github.com/40626785/SEGroup.git
    id: ThresholdMapViewModel
    path: EnvironmentManager/ViewModels/ThresholdMapViewModel.cs
    startLine: 8
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.ViewModels
  summary: Code-behind the Threshold Map
  example: []
  syntax:
    content: public class ThresholdMapViewModel
    content.vb: Public Class ThresholdMapViewModel
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: EnvironmentManager.ViewModels.ThresholdMapViewModel.#ctor(EnvironmentManager.Interfaces.ISensorDataStore,EnvironmentManager.Interfaces.ISensorThresholdService)
  commentId: M:EnvironmentManager.ViewModels.ThresholdMapViewModel.#ctor(EnvironmentManager.Interfaces.ISensorDataStore,EnvironmentManager.Interfaces.ISensorThresholdService)
  id: '#ctor(EnvironmentManager.Interfaces.ISensorDataStore,EnvironmentManager.Interfaces.ISensorThresholdService)'
  parent: EnvironmentManager.ViewModels.ThresholdMapViewModel
  langs:
  - csharp
  - vb
  name: ThresholdMapViewModel(ISensorDataStore, ISensorThresholdService)
  nameWithType: ThresholdMapViewModel.ThresholdMapViewModel(ISensorDataStore, ISensorThresholdService)
  fullName: EnvironmentManager.ViewModels.ThresholdMapViewModel.ThresholdMapViewModel(EnvironmentManager.Interfaces.ISensorDataStore, EnvironmentManager.Interfaces.ISensorThresholdService)
  type: Constructor
  source:
    remote:
      path: EnvironmentManager/ViewModels/ThresholdMapViewModel.cs
      branch: feat/5-threshold-map
      repo: https://github.com/40626785/SEGroup.git
    id: .ctor
    path: EnvironmentManager/ViewModels/ThresholdMapViewModel.cs
    startLine: 13
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.ViewModels
  syntax:
    content: public ThresholdMapViewModel(ISensorDataStore context, ISensorThresholdService sensorThresholdService)
    parameters:
    - id: context
      type: EnvironmentManager.Interfaces.ISensorDataStore
    - id: sensorThresholdService
      type: EnvironmentManager.Interfaces.ISensorThresholdService
    content.vb: Public Sub New(context As ISensorDataStore, sensorThresholdService As ISensorThresholdService)
  overload: EnvironmentManager.ViewModels.ThresholdMapViewModel.#ctor*
  nameWithType.vb: ThresholdMapViewModel.New(ISensorDataStore, ISensorThresholdService)
  fullName.vb: EnvironmentManager.ViewModels.ThresholdMapViewModel.New(EnvironmentManager.Interfaces.ISensorDataStore, EnvironmentManager.Interfaces.ISensorThresholdService)
  name.vb: New(ISensorDataStore, ISensorThresholdService)
- uid: EnvironmentManager.ViewModels.ThresholdMapViewModel.GetSensorBreachPins
  commentId: M:EnvironmentManager.ViewModels.ThresholdMapViewModel.GetSensorBreachPins
  id: GetSensorBreachPins
  parent: EnvironmentManager.ViewModels.ThresholdMapViewModel
  langs:
  - csharp
  - vb
  name: GetSensorBreachPins()
  nameWithType: ThresholdMapViewModel.GetSensorBreachPins()
  fullName: EnvironmentManager.ViewModels.ThresholdMapViewModel.GetSensorBreachPins()
  type: Method
  source:
    remote:
      path: EnvironmentManager/ViewModels/ThresholdMapViewModel.cs
      branch: feat/5-threshold-map
      repo: https://github.com/40626785/SEGroup.git
    id: GetSensorBreachPins
    path: EnvironmentManager/ViewModels/ThresholdMapViewModel.cs
    startLine: 23
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.ViewModels
  summary: Creates MapPins based on all stored breaches of Threshold Rules
  example: []
  syntax:
    content: public List<MapPinViewModel> GetSensorBreachPins()
    return:
      type: System.Collections.Generic.List{EnvironmentManager.Models.MapPinViewModel}
      description: List of MapPins representing Threshold Breaches
    content.vb: Public Function GetSensorBreachPins() As List(Of MapPinViewModel)
  overload: EnvironmentManager.ViewModels.ThresholdMapViewModel.GetSensorBreachPins*
references:
- uid: EnvironmentManager.ViewModels
  commentId: N:EnvironmentManager.ViewModels
  href: EnvironmentManager.html
  name: EnvironmentManager.ViewModels
  nameWithType: EnvironmentManager.ViewModels
  fullName: EnvironmentManager.ViewModels
  spec.csharp:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.ViewModels
    name: ViewModels
    href: EnvironmentManager.ViewModels.html
  spec.vb:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.ViewModels
    name: ViewModels
    href: EnvironmentManager.ViewModels.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: EnvironmentManager.ViewModels.ThresholdMapViewModel.#ctor*
  commentId: Overload:EnvironmentManager.ViewModels.ThresholdMapViewModel.#ctor
  href: EnvironmentManager.ViewModels.ThresholdMapViewModel.html#EnvironmentManager_ViewModels_ThresholdMapViewModel__ctor_EnvironmentManager_Interfaces_ISensorDataStore_EnvironmentManager_Interfaces_ISensorThresholdService_
  name: ThresholdMapViewModel
  nameWithType: ThresholdMapViewModel.ThresholdMapViewModel
  fullName: EnvironmentManager.ViewModels.ThresholdMapViewModel.ThresholdMapViewModel
  nameWithType.vb: ThresholdMapViewModel.New
  fullName.vb: EnvironmentManager.ViewModels.ThresholdMapViewModel.New
  name.vb: New
- uid: EnvironmentManager.Interfaces.ISensorDataStore
  commentId: T:EnvironmentManager.Interfaces.ISensorDataStore
  parent: EnvironmentManager.Interfaces
  href: EnvironmentManager.Interfaces.ISensorDataStore.html
  name: ISensorDataStore
  nameWithType: ISensorDataStore
  fullName: EnvironmentManager.Interfaces.ISensorDataStore
- uid: EnvironmentManager.Interfaces.ISensorThresholdService
  commentId: T:EnvironmentManager.Interfaces.ISensorThresholdService
  parent: EnvironmentManager.Interfaces
  href: EnvironmentManager.Interfaces.ISensorThresholdService.html
  name: ISensorThresholdService
  nameWithType: ISensorThresholdService
  fullName: EnvironmentManager.Interfaces.ISensorThresholdService
- uid: EnvironmentManager.Interfaces
  commentId: N:EnvironmentManager.Interfaces
  href: EnvironmentManager.html
  name: EnvironmentManager.Interfaces
  nameWithType: EnvironmentManager.Interfaces
  fullName: EnvironmentManager.Interfaces
  spec.csharp:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Interfaces
    name: Interfaces
    href: EnvironmentManager.Interfaces.html
  spec.vb:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Interfaces
    name: Interfaces
    href: EnvironmentManager.Interfaces.html
- uid: EnvironmentManager.ViewModels.ThresholdMapViewModel.GetSensorBreachPins*
  commentId: Overload:EnvironmentManager.ViewModels.ThresholdMapViewModel.GetSensorBreachPins
  href: EnvironmentManager.ViewModels.ThresholdMapViewModel.html#EnvironmentManager_ViewModels_ThresholdMapViewModel_GetSensorBreachPins
  name: GetSensorBreachPins
  nameWithType: ThresholdMapViewModel.GetSensorBreachPins
  fullName: EnvironmentManager.ViewModels.ThresholdMapViewModel.GetSensorBreachPins
- uid: System.Collections.Generic.List{EnvironmentManager.Models.MapPinViewModel}
  commentId: T:System.Collections.Generic.List{EnvironmentManager.Models.MapPinViewModel}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<MapPinViewModel>
  nameWithType: List<MapPinViewModel>
  fullName: System.Collections.Generic.List<EnvironmentManager.Models.MapPinViewModel>
  nameWithType.vb: List(Of MapPinViewModel)
  fullName.vb: System.Collections.Generic.List(Of EnvironmentManager.Models.MapPinViewModel)
  name.vb: List(Of MapPinViewModel)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: EnvironmentManager.Models.MapPinViewModel
    name: MapPinViewModel
    href: EnvironmentManager.Models.MapPinViewModel.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: EnvironmentManager.Models.MapPinViewModel
    name: MapPinViewModel
    href: EnvironmentManager.Models.MapPinViewModel.html
  - name: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
