### YamlMime:ManagedReference
items:
- uid: EnvironmentManager.Test
  commentId: N:EnvironmentManager.Test
  id: EnvironmentManager.Test
  children:
  - EnvironmentManager.Test.AddSensorViewModelTests
  - EnvironmentManager.Test.AllMaintenanceViewModelTests
  - EnvironmentManager.Test.EditSensorViewModelTests
  - EnvironmentManager.Test.MaintenanceViewModelTests
  - EnvironmentManager.Test.SensorViewModelTests
  - EnvironmentManager.Test.TestUtils
  langs:
  - csharp
  - vb
  name: EnvironmentManager.Test
  nameWithType: EnvironmentManager.Test
  fullName: EnvironmentManager.Test
  type: Namespace
  assemblies:
  - EnvironmentManager.Test
references:
- uid: EnvironmentManager.Test.AddSensorViewModelTests
  commentId: T:EnvironmentManager.Test.AddSensorViewModelTests
  href: EnvironmentManager.Test.AddSensorViewModelTests.html
  name: AddSensorViewModelTests
  nameWithType: AddSensorViewModelTests
  fullName: EnvironmentManager.Test.AddSensorViewModelTests
- uid: EnvironmentManager.Test.AllMaintenanceViewModelTests
  commentId: T:EnvironmentManager.Test.AllMaintenanceViewModelTests
  href: EnvironmentManager.Test.AllMaintenanceViewModelTests.html
  name: AllMaintenanceViewModelTests
  nameWithType: AllMaintenanceViewModelTests
  fullName: EnvironmentManager.Test.AllMaintenanceViewModelTests
- uid: EnvironmentManager.Test.EditSensorViewModelTests
  commentId: T:EnvironmentManager.Test.EditSensorViewModelTests
  href: EnvironmentManager.Test.EditSensorViewModelTests.html
  name: EditSensorViewModelTests
  nameWithType: EditSensorViewModelTests
  fullName: EnvironmentManager.Test.EditSensorViewModelTests
- uid: EnvironmentManager.Test.MaintenanceViewModelTests
  commentId: T:EnvironmentManager.Test.MaintenanceViewModelTests
  href: EnvironmentManager.Test.MaintenanceViewModelTests.html
  name: MaintenanceViewModelTests
  nameWithType: MaintenanceViewModelTests
  fullName: EnvironmentManager.Test.MaintenanceViewModelTests
- uid: EnvironmentManager.Test.SensorViewModelTests
  commentId: T:EnvironmentManager.Test.SensorViewModelTests
  href: EnvironmentManager.Test.SensorViewModelTests.html
  name: SensorViewModelTests
  nameWithType: SensorViewModelTests
  fullName: EnvironmentManager.Test.SensorViewModelTests
- uid: EnvironmentManager.Test.TestUtils
  commentId: T:EnvironmentManager.Test.TestUtils
  href: EnvironmentManager.Test.TestUtils.html
  name: TestUtils
  nameWithType: TestUtils
  fullName: EnvironmentManager.Test.TestUtils
