### YamlMime:ManagedReference
items:
- uid: EnvironmentManager.ViewModels.AboutViewModel
  commentId: T:EnvironmentManager.ViewModels.AboutViewModel
  id: AboutViewModel
  parent: EnvironmentManager.ViewModels
  children:
  - EnvironmentManager.ViewModels.AboutViewModel.#ctor
  - EnvironmentManager.ViewModels.AboutViewModel.Message
  - EnvironmentManager.ViewModels.AboutViewModel.MoreInfoUrl
  - EnvironmentManager.ViewModels.AboutViewModel.ShowMoreInfoCommand
  - EnvironmentManager.ViewModels.AboutViewModel.Title
  - EnvironmentManager.ViewModels.AboutViewModel.Version
  langs:
  - csharp
  - vb
  name: AboutViewModel
  nameWithType: AboutViewModel
  fullName: EnvironmentManager.ViewModels.AboutViewModel
  type: Class
  source:
    remote:
      path: EnvironmentManager/ViewModels/AboutViewModel.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: AboutViewModel
    path: EnvironmentManager/ViewModels/AboutViewModel.cs
    startLine: 5
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.ViewModels
  syntax:
    content: public class AboutViewModel
    content.vb: Public Class AboutViewModel
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: EnvironmentManager.ViewModels.AboutViewModel.Title
  commentId: P:EnvironmentManager.ViewModels.AboutViewModel.Title
  id: Title
  parent: EnvironmentManager.ViewModels.AboutViewModel
  langs:
  - csharp
  - vb
  name: Title
  nameWithType: AboutViewModel.Title
  fullName: EnvironmentManager.ViewModels.AboutViewModel.Title
  type: Property
  source:
    remote:
      path: EnvironmentManager/ViewModels/AboutViewModel.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: Title
    path: EnvironmentManager/ViewModels/AboutViewModel.cs
    startLine: 7
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.ViewModels
  syntax:
    content: public string Title { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Title As String
  overload: EnvironmentManager.ViewModels.AboutViewModel.Title*
- uid: EnvironmentManager.ViewModels.AboutViewModel.Version
  commentId: P:EnvironmentManager.ViewModels.AboutViewModel.Version
  id: Version
  parent: EnvironmentManager.ViewModels.AboutViewModel
  langs:
  - csharp
  - vb
  name: Version
  nameWithType: AboutViewModel.Version
  fullName: EnvironmentManager.ViewModels.AboutViewModel.Version
  type: Property
  source:
    remote:
      path: EnvironmentManager/ViewModels/AboutViewModel.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: Version
    path: EnvironmentManager/ViewModels/AboutViewModel.cs
    startLine: 8
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.ViewModels
  syntax:
    content: public string Version { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Version As String
  overload: EnvironmentManager.ViewModels.AboutViewModel.Version*
- uid: EnvironmentManager.ViewModels.AboutViewModel.MoreInfoUrl
  commentId: P:EnvironmentManager.ViewModels.AboutViewModel.MoreInfoUrl
  id: MoreInfoUrl
  parent: EnvironmentManager.ViewModels.AboutViewModel
  langs:
  - csharp
  - vb
  name: MoreInfoUrl
  nameWithType: AboutViewModel.MoreInfoUrl
  fullName: EnvironmentManager.ViewModels.AboutViewModel.MoreInfoUrl
  type: Property
  source:
    remote:
      path: EnvironmentManager/ViewModels/AboutViewModel.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: MoreInfoUrl
    path: EnvironmentManager/ViewModels/AboutViewModel.cs
    startLine: 9
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.ViewModels
  syntax:
    content: public string MoreInfoUrl { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property MoreInfoUrl As String
  overload: EnvironmentManager.ViewModels.AboutViewModel.MoreInfoUrl*
- uid: EnvironmentManager.ViewModels.AboutViewModel.Message
  commentId: P:EnvironmentManager.ViewModels.AboutViewModel.Message
  id: Message
  parent: EnvironmentManager.ViewModels.AboutViewModel
  langs:
  - csharp
  - vb
  name: Message
  nameWithType: AboutViewModel.Message
  fullName: EnvironmentManager.ViewModels.AboutViewModel.Message
  type: Property
  source:
    remote:
      path: EnvironmentManager/ViewModels/AboutViewModel.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: Message
    path: EnvironmentManager/ViewModels/AboutViewModel.cs
    startLine: 10
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.ViewModels
  syntax:
    content: public string Message { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Message As String
  overload: EnvironmentManager.ViewModels.AboutViewModel.Message*
- uid: EnvironmentManager.ViewModels.AboutViewModel.ShowMoreInfoCommand
  commentId: P:EnvironmentManager.ViewModels.AboutViewModel.ShowMoreInfoCommand
  id: ShowMoreInfoCommand
  parent: EnvironmentManager.ViewModels.AboutViewModel
  langs:
  - csharp
  - vb
  name: ShowMoreInfoCommand
  nameWithType: AboutViewModel.ShowMoreInfoCommand
  fullName: EnvironmentManager.ViewModels.AboutViewModel.ShowMoreInfoCommand
  type: Property
  source:
    remote:
      path: EnvironmentManager/ViewModels/AboutViewModel.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: ShowMoreInfoCommand
    path: EnvironmentManager/ViewModels/AboutViewModel.cs
    startLine: 11
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.ViewModels
  syntax:
    content: public ICommand ShowMoreInfoCommand { get; }
    parameters: []
    return:
      type: System.Windows.Input.ICommand
    content.vb: Public ReadOnly Property ShowMoreInfoCommand As ICommand
  overload: EnvironmentManager.ViewModels.AboutViewModel.ShowMoreInfoCommand*
- uid: EnvironmentManager.ViewModels.AboutViewModel.#ctor
  commentId: M:EnvironmentManager.ViewModels.AboutViewModel.#ctor
  id: '#ctor'
  parent: EnvironmentManager.ViewModels.AboutViewModel
  langs:
  - csharp
  - vb
  name: AboutViewModel()
  nameWithType: AboutViewModel.AboutViewModel()
  fullName: EnvironmentManager.ViewModels.AboutViewModel.AboutViewModel()
  type: Constructor
  source:
    remote:
      path: EnvironmentManager/ViewModels/AboutViewModel.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: .ctor
    path: EnvironmentManager/ViewModels/AboutViewModel.cs
    startLine: 13
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.ViewModels
  syntax:
    content: public AboutViewModel()
    content.vb: Public Sub New()
  overload: EnvironmentManager.ViewModels.AboutViewModel.#ctor*
  nameWithType.vb: AboutViewModel.New()
  fullName.vb: EnvironmentManager.ViewModels.AboutViewModel.New()
  name.vb: New()
references:
- uid: EnvironmentManager.ViewModels
  commentId: N:EnvironmentManager.ViewModels
  href: EnvironmentManager.html
  name: EnvironmentManager.ViewModels
  nameWithType: EnvironmentManager.ViewModels
  fullName: EnvironmentManager.ViewModels
  spec.csharp:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.ViewModels
    name: ViewModels
    href: EnvironmentManager.ViewModels.html
  spec.vb:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.ViewModels
    name: ViewModels
    href: EnvironmentManager.ViewModels.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: EnvironmentManager.ViewModels.AboutViewModel.Title*
  commentId: Overload:EnvironmentManager.ViewModels.AboutViewModel.Title
  href: EnvironmentManager.ViewModels.AboutViewModel.html#EnvironmentManager_ViewModels_AboutViewModel_Title
  name: Title
  nameWithType: AboutViewModel.Title
  fullName: EnvironmentManager.ViewModels.AboutViewModel.Title
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: EnvironmentManager.ViewModels.AboutViewModel.Version*
  commentId: Overload:EnvironmentManager.ViewModels.AboutViewModel.Version
  href: EnvironmentManager.ViewModels.AboutViewModel.html#EnvironmentManager_ViewModels_AboutViewModel_Version
  name: Version
  nameWithType: AboutViewModel.Version
  fullName: EnvironmentManager.ViewModels.AboutViewModel.Version
- uid: EnvironmentManager.ViewModels.AboutViewModel.MoreInfoUrl*
  commentId: Overload:EnvironmentManager.ViewModels.AboutViewModel.MoreInfoUrl
  href: EnvironmentManager.ViewModels.AboutViewModel.html#EnvironmentManager_ViewModels_AboutViewModel_MoreInfoUrl
  name: MoreInfoUrl
  nameWithType: AboutViewModel.MoreInfoUrl
  fullName: EnvironmentManager.ViewModels.AboutViewModel.MoreInfoUrl
- uid: EnvironmentManager.ViewModels.AboutViewModel.Message*
  commentId: Overload:EnvironmentManager.ViewModels.AboutViewModel.Message
  href: EnvironmentManager.ViewModels.AboutViewModel.html#EnvironmentManager_ViewModels_AboutViewModel_Message
  name: Message
  nameWithType: AboutViewModel.Message
  fullName: EnvironmentManager.ViewModels.AboutViewModel.Message
- uid: EnvironmentManager.ViewModels.AboutViewModel.ShowMoreInfoCommand*
  commentId: Overload:EnvironmentManager.ViewModels.AboutViewModel.ShowMoreInfoCommand
  href: EnvironmentManager.ViewModels.AboutViewModel.html#EnvironmentManager_ViewModels_AboutViewModel_ShowMoreInfoCommand
  name: ShowMoreInfoCommand
  nameWithType: AboutViewModel.ShowMoreInfoCommand
  fullName: EnvironmentManager.ViewModels.AboutViewModel.ShowMoreInfoCommand
- uid: System.Windows.Input.ICommand
  commentId: T:System.Windows.Input.ICommand
  parent: System.Windows.Input
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.windows.input.icommand
  name: ICommand
  nameWithType: ICommand
  fullName: System.Windows.Input.ICommand
- uid: System.Windows.Input
  commentId: N:System.Windows.Input
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Windows.Input
  nameWithType: System.Windows.Input
  fullName: System.Windows.Input
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Windows
    name: Windows
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows
  - name: .
  - uid: System.Windows.Input
    name: Input
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows.input
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Windows
    name: Windows
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows
  - name: .
  - uid: System.Windows.Input
    name: Input
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows.input
- uid: EnvironmentManager.ViewModels.AboutViewModel.#ctor*
  commentId: Overload:EnvironmentManager.ViewModels.AboutViewModel.#ctor
  href: EnvironmentManager.ViewModels.AboutViewModel.html#EnvironmentManager_ViewModels_AboutViewModel__ctor
  name: AboutViewModel
  nameWithType: AboutViewModel.AboutViewModel
  fullName: EnvironmentManager.ViewModels.AboutViewModel.AboutViewModel
  nameWithType.vb: AboutViewModel.New
  fullName.vb: EnvironmentManager.ViewModels.AboutViewModel.New
  name.vb: New
