### YamlMime:ManagedReference
items:
- uid: EnvironmentManager.Models.ArchiveWeatherData
  commentId: T:EnvironmentManager.Models.ArchiveWeatherData
  id: ArchiveWeatherData
  parent: EnvironmentManager.Models
  children:
  - EnvironmentManager.Models.ArchiveWeatherData.Date_Time
  - EnvironmentManager.Models.ArchiveWeatherData.Relative_humidity_2m
  - EnvironmentManager.Models.ArchiveWeatherData.Temperature_2m
  - EnvironmentManager.Models.ArchiveWeatherData.Wind_direction_10m
  - EnvironmentManager.Models.ArchiveWeatherData.Wind_speed_10m
  langs:
  - csharp
  - vb
  name: ArchiveWeatherData
  nameWithType: ArchiveWeatherData
  fullName: EnvironmentManager.Models.ArchiveWeatherData
  type: Class
  source:
    remote:
      path: EnvironmentManager/Models/ArchiveWeatherData.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: ArchiveWeatherData
    path: EnvironmentManager/Models/ArchiveWeatherData.cs
    startLine: 6
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Models
  syntax:
    content: public class ArchiveWeatherData
    content.vb: Public Class ArchiveWeatherData
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: EnvironmentManager.Models.ArchiveWeatherData.Date_Time
  commentId: P:EnvironmentManager.Models.ArchiveWeatherData.Date_Time
  id: Date_Time
  parent: EnvironmentManager.Models.ArchiveWeatherData
  langs:
  - csharp
  - vb
  name: Date_Time
  nameWithType: ArchiveWeatherData.Date_Time
  fullName: EnvironmentManager.Models.ArchiveWeatherData.Date_Time
  type: Property
  source:
    remote:
      path: EnvironmentManager/Models/ArchiveWeatherData.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: Date_Time
    path: EnvironmentManager/Models/ArchiveWeatherData.cs
    startLine: 8
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Models
  syntax:
    content: >-
      [Key]

      [Column(TypeName = "datetime")]

      public DateTime Date_Time { get; set; }
    parameters: []
    return:
      type: System.DateTime
    content.vb: >-
      <Key>

      <Column(TypeName:="datetime")>

      Public Property Date_Time As Date
  overload: EnvironmentManager.Models.ArchiveWeatherData.Date_Time*
  attributes:
  - type: System.ComponentModel.DataAnnotations.KeyAttribute
    ctor: System.ComponentModel.DataAnnotations.KeyAttribute.#ctor
    arguments: []
  - type: System.ComponentModel.DataAnnotations.Schema.ColumnAttribute
    ctor: System.ComponentModel.DataAnnotations.Schema.ColumnAttribute.#ctor
    arguments: []
    namedArguments:
    - name: TypeName
      type: System.String
      value: datetime
- uid: EnvironmentManager.Models.ArchiveWeatherData.Temperature_2m
  commentId: P:EnvironmentManager.Models.ArchiveWeatherData.Temperature_2m
  id: Temperature_2m
  parent: EnvironmentManager.Models.ArchiveWeatherData
  langs:
  - csharp
  - vb
  name: Temperature_2m
  nameWithType: ArchiveWeatherData.Temperature_2m
  fullName: EnvironmentManager.Models.ArchiveWeatherData.Temperature_2m
  type: Property
  source:
    remote:
      path: EnvironmentManager/Models/ArchiveWeatherData.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: Temperature_2m
    path: EnvironmentManager/Models/ArchiveWeatherData.cs
    startLine: 12
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Models
  syntax:
    content: public double Temperature_2m { get; set; }
    parameters: []
    return:
      type: System.Double
    content.vb: Public Property Temperature_2m As Double
  overload: EnvironmentManager.Models.ArchiveWeatherData.Temperature_2m*
- uid: EnvironmentManager.Models.ArchiveWeatherData.Relative_humidity_2m
  commentId: P:EnvironmentManager.Models.ArchiveWeatherData.Relative_humidity_2m
  id: Relative_humidity_2m
  parent: EnvironmentManager.Models.ArchiveWeatherData
  langs:
  - csharp
  - vb
  name: Relative_humidity_2m
  nameWithType: ArchiveWeatherData.Relative_humidity_2m
  fullName: EnvironmentManager.Models.ArchiveWeatherData.Relative_humidity_2m
  type: Property
  source:
    remote:
      path: EnvironmentManager/Models/ArchiveWeatherData.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: Relative_humidity_2m
    path: EnvironmentManager/Models/ArchiveWeatherData.cs
    startLine: 14
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Models
  syntax:
    content: public double Relative_humidity_2m { get; set; }
    parameters: []
    return:
      type: System.Double
    content.vb: Public Property Relative_humidity_2m As Double
  overload: EnvironmentManager.Models.ArchiveWeatherData.Relative_humidity_2m*
- uid: EnvironmentManager.Models.ArchiveWeatherData.Wind_speed_10m
  commentId: P:EnvironmentManager.Models.ArchiveWeatherData.Wind_speed_10m
  id: Wind_speed_10m
  parent: EnvironmentManager.Models.ArchiveWeatherData
  langs:
  - csharp
  - vb
  name: Wind_speed_10m
  nameWithType: ArchiveWeatherData.Wind_speed_10m
  fullName: EnvironmentManager.Models.ArchiveWeatherData.Wind_speed_10m
  type: Property
  source:
    remote:
      path: EnvironmentManager/Models/ArchiveWeatherData.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: Wind_speed_10m
    path: EnvironmentManager/Models/ArchiveWeatherData.cs
    startLine: 16
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Models
  syntax:
    content: public double Wind_speed_10m { get; set; }
    parameters: []
    return:
      type: System.Double
    content.vb: Public Property Wind_speed_10m As Double
  overload: EnvironmentManager.Models.ArchiveWeatherData.Wind_speed_10m*
- uid: EnvironmentManager.Models.ArchiveWeatherData.Wind_direction_10m
  commentId: P:EnvironmentManager.Models.ArchiveWeatherData.Wind_direction_10m
  id: Wind_direction_10m
  parent: EnvironmentManager.Models.ArchiveWeatherData
  langs:
  - csharp
  - vb
  name: Wind_direction_10m
  nameWithType: ArchiveWeatherData.Wind_direction_10m
  fullName: EnvironmentManager.Models.ArchiveWeatherData.Wind_direction_10m
  type: Property
  source:
    remote:
      path: EnvironmentManager/Models/ArchiveWeatherData.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: Wind_direction_10m
    path: EnvironmentManager/Models/ArchiveWeatherData.cs
    startLine: 18
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Models
  syntax:
    content: public double Wind_direction_10m { get; set; }
    parameters: []
    return:
      type: System.Double
    content.vb: Public Property Wind_direction_10m As Double
  overload: EnvironmentManager.Models.ArchiveWeatherData.Wind_direction_10m*
references:
- uid: EnvironmentManager.Models
  commentId: N:EnvironmentManager.Models
  href: EnvironmentManager.html
  name: EnvironmentManager.Models
  nameWithType: EnvironmentManager.Models
  fullName: EnvironmentManager.Models
  spec.csharp:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Models
    name: Models
    href: EnvironmentManager.Models.html
  spec.vb:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Models
    name: Models
    href: EnvironmentManager.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: EnvironmentManager.Models.ArchiveWeatherData.Date_Time*
  commentId: Overload:EnvironmentManager.Models.ArchiveWeatherData.Date_Time
  href: EnvironmentManager.Models.ArchiveWeatherData.html#EnvironmentManager_Models_ArchiveWeatherData_Date_Time
  name: Date_Time
  nameWithType: ArchiveWeatherData.Date_Time
  fullName: EnvironmentManager.Models.ArchiveWeatherData.Date_Time
- uid: System.DateTime
  commentId: T:System.DateTime
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.datetime
  name: DateTime
  nameWithType: DateTime
  fullName: System.DateTime
  nameWithType.vb: Date
  fullName.vb: Date
  name.vb: Date
- uid: EnvironmentManager.Models.ArchiveWeatherData.Temperature_2m*
  commentId: Overload:EnvironmentManager.Models.ArchiveWeatherData.Temperature_2m
  href: EnvironmentManager.Models.ArchiveWeatherData.html#EnvironmentManager_Models_ArchiveWeatherData_Temperature_2m
  name: Temperature_2m
  nameWithType: ArchiveWeatherData.Temperature_2m
  fullName: EnvironmentManager.Models.ArchiveWeatherData.Temperature_2m
- uid: System.Double
  commentId: T:System.Double
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.double
  name: double
  nameWithType: double
  fullName: double
  nameWithType.vb: Double
  fullName.vb: Double
  name.vb: Double
- uid: EnvironmentManager.Models.ArchiveWeatherData.Relative_humidity_2m*
  commentId: Overload:EnvironmentManager.Models.ArchiveWeatherData.Relative_humidity_2m
  href: EnvironmentManager.Models.ArchiveWeatherData.html#EnvironmentManager_Models_ArchiveWeatherData_Relative_humidity_2m
  name: Relative_humidity_2m
  nameWithType: ArchiveWeatherData.Relative_humidity_2m
  fullName: EnvironmentManager.Models.ArchiveWeatherData.Relative_humidity_2m
- uid: EnvironmentManager.Models.ArchiveWeatherData.Wind_speed_10m*
  commentId: Overload:EnvironmentManager.Models.ArchiveWeatherData.Wind_speed_10m
  href: EnvironmentManager.Models.ArchiveWeatherData.html#EnvironmentManager_Models_ArchiveWeatherData_Wind_speed_10m
  name: Wind_speed_10m
  nameWithType: ArchiveWeatherData.Wind_speed_10m
  fullName: EnvironmentManager.Models.ArchiveWeatherData.Wind_speed_10m
- uid: EnvironmentManager.Models.ArchiveWeatherData.Wind_direction_10m*
  commentId: Overload:EnvironmentManager.Models.ArchiveWeatherData.Wind_direction_10m
  href: EnvironmentManager.Models.ArchiveWeatherData.html#EnvironmentManager_Models_ArchiveWeatherData_Wind_direction_10m
  name: Wind_direction_10m
  nameWithType: ArchiveWeatherData.Wind_direction_10m
  fullName: EnvironmentManager.Models.ArchiveWeatherData.Wind_direction_10m
