### YamlMime:ManagedReference
items:
- uid: EnvironmentManager.Views
  commentId: N:EnvironmentManager.Views
  id: EnvironmentManager.Views
  children:
  - EnvironmentManager.Views.AboutPage
  - EnvironmentManager.Views.AddSensorPage
  - EnvironmentManager.Views.AllMaintenancePage
  - EnvironmentManager.Views.EditSensorPage
  - EnvironmentManager.Views.EditUserPage
  - EnvironmentManager.Views.HistoricalData
  - EnvironmentManager.Views.HistoricalDataViewerPage
  - EnvironmentManager.Views.HomePage
  - EnvironmentManager.Views.LoginPage
  - EnvironmentManager.Views.MaintenancePage
  - EnvironmentManager.Views.SensorMonitoringPage
  - EnvironmentManager.Views.SensorPage
  - EnvironmentManager.Views.ThresholdMapPage
  - EnvironmentManager.Views.UserManagementPage
  langs:
  - csharp
  - vb
  name: EnvironmentManager.Views
  nameWithType: EnvironmentManager.Views
  fullName: EnvironmentManager.Views
  type: Namespace
  assemblies:
  - EnvironmentManager
references:
- uid: EnvironmentManager.Views.AboutPage
  commentId: T:EnvironmentManager.Views.AboutPage
  href: EnvironmentManager.Views.AboutPage.html
  name: AboutPage
  nameWithType: AboutPage
  fullName: EnvironmentManager.Views.AboutPage
- uid: EnvironmentManager.Views.AddSensorPage
  commentId: T:EnvironmentManager.Views.AddSensorPage
  href: EnvironmentManager.Views.AddSensorPage.html
  name: AddSensorPage
  nameWithType: AddSensorPage
  fullName: EnvironmentManager.Views.AddSensorPage
- uid: EnvironmentManager.Views.AllMaintenancePage
  commentId: T:EnvironmentManager.Views.AllMaintenancePage
  href: EnvironmentManager.Views.AllMaintenancePage.html
  name: AllMaintenancePage
  nameWithType: AllMaintenancePage
  fullName: EnvironmentManager.Views.AllMaintenancePage
- uid: EnvironmentManager.Views.EditSensorPage
  commentId: T:EnvironmentManager.Views.EditSensorPage
  href: EnvironmentManager.Views.EditSensorPage.html
  name: EditSensorPage
  nameWithType: EditSensorPage
  fullName: EnvironmentManager.Views.EditSensorPage
- uid: EnvironmentManager.Views.EditUserPage
  commentId: T:EnvironmentManager.Views.EditUserPage
  href: EnvironmentManager.Views.EditUserPage.html
  name: EditUserPage
  nameWithType: EditUserPage
  fullName: EnvironmentManager.Views.EditUserPage
- uid: EnvironmentManager.Views.HistoricalData
  commentId: T:EnvironmentManager.Views.HistoricalData
  href: EnvironmentManager.Views.HistoricalData.html
  name: HistoricalData
  nameWithType: HistoricalData
  fullName: EnvironmentManager.Views.HistoricalData
- uid: EnvironmentManager.Views.HistoricalDataViewerPage
  commentId: T:EnvironmentManager.Views.HistoricalDataViewerPage
  href: EnvironmentManager.Views.HistoricalDataViewerPage.html
  name: HistoricalDataViewerPage
  nameWithType: HistoricalDataViewerPage
  fullName: EnvironmentManager.Views.HistoricalDataViewerPage
- uid: EnvironmentManager.Views.HomePage
  commentId: T:EnvironmentManager.Views.HomePage
  href: EnvironmentManager.Views.HomePage.html
  name: HomePage
  nameWithType: HomePage
  fullName: EnvironmentManager.Views.HomePage
- uid: EnvironmentManager.Views.LoginPage
  commentId: T:EnvironmentManager.Views.LoginPage
  href: EnvironmentManager.Views.LoginPage.html
  name: LoginPage
  nameWithType: LoginPage
  fullName: EnvironmentManager.Views.LoginPage
- uid: EnvironmentManager.Views.MaintenancePage
  commentId: T:EnvironmentManager.Views.MaintenancePage
  href: EnvironmentManager.Views.MaintenancePage.html
  name: MaintenancePage
  nameWithType: MaintenancePage
  fullName: EnvironmentManager.Views.MaintenancePage
- uid: EnvironmentManager.Views.SensorMonitoringPage
  commentId: T:EnvironmentManager.Views.SensorMonitoringPage
  href: EnvironmentManager.Views.SensorMonitoringPage.html
  name: SensorMonitoringPage
  nameWithType: SensorMonitoringPage
  fullName: EnvironmentManager.Views.SensorMonitoringPage
- uid: EnvironmentManager.Views.SensorPage
  commentId: T:EnvironmentManager.Views.SensorPage
  href: EnvironmentManager.Views.SensorPage.html
  name: SensorPage
  nameWithType: SensorPage
  fullName: EnvironmentManager.Views.SensorPage
- uid: EnvironmentManager.Views.ThresholdMapPage
  commentId: T:EnvironmentManager.Views.ThresholdMapPage
  href: EnvironmentManager.Views.ThresholdMapPage.html
  name: ThresholdMapPage
  nameWithType: ThresholdMapPage
  fullName: EnvironmentManager.Views.ThresholdMapPage
- uid: EnvironmentManager.Views.UserManagementPage
  commentId: T:EnvironmentManager.Views.UserManagementPage
  href: EnvironmentManager.Views.UserManagementPage.html
  name: UserManagementPage
  nameWithType: UserManagementPage
  fullName: EnvironmentManager.Views.UserManagementPage
