### YamlMime:ManagedReference
items:
- uid: EnvironmentManager.Models.Role
  commentId: T:EnvironmentManager.Models.Role
  id: Role
  parent: EnvironmentManager.Models
  children:
  - EnvironmentManager.Models.Role.CreatedDate
  - EnvironmentManager.Models.Role.Description
  - EnvironmentManager.Models.Role.LastModifiedDate
  - EnvironmentManager.Models.Role.RoleId
  - EnvironmentManager.Models.Role.RoleName
  langs:
  - csharp
  - vb
  name: Role
  nameWithType: Role
  fullName: EnvironmentManager.Models.Role
  type: Class
  source:
    remote:
      path: EnvironmentManager/Models/Role.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: Role
    path: EnvironmentManager/Models/Role.cs
    startLine: 6
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Models
  syntax:
    content: >-
      [Table("Roles")]

      public class Role
    content.vb: >-
      <Table("Roles")>

      Public Class Role
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.ComponentModel.DataAnnotations.Schema.TableAttribute
    ctor: System.ComponentModel.DataAnnotations.Schema.TableAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Roles
- uid: EnvironmentManager.Models.Role.RoleId
  commentId: P:EnvironmentManager.Models.Role.RoleId
  id: RoleId
  parent: EnvironmentManager.Models.Role
  langs:
  - csharp
  - vb
  name: RoleId
  nameWithType: Role.RoleId
  fullName: EnvironmentManager.Models.Role.RoleId
  type: Property
  source:
    remote:
      path: EnvironmentManager/Models/Role.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: RoleId
    path: EnvironmentManager/Models/Role.cs
    startLine: 9
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Models
  syntax:
    content: >-
      [Key]

      public int RoleId { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: >-
      <Key>

      Public Property RoleId As Integer
  overload: EnvironmentManager.Models.Role.RoleId*
  attributes:
  - type: System.ComponentModel.DataAnnotations.KeyAttribute
    ctor: System.ComponentModel.DataAnnotations.KeyAttribute.#ctor
    arguments: []
- uid: EnvironmentManager.Models.Role.RoleName
  commentId: P:EnvironmentManager.Models.Role.RoleName
  id: RoleName
  parent: EnvironmentManager.Models.Role
  langs:
  - csharp
  - vb
  name: RoleName
  nameWithType: Role.RoleName
  fullName: EnvironmentManager.Models.Role.RoleName
  type: Property
  source:
    remote:
      path: EnvironmentManager/Models/Role.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: RoleName
    path: EnvironmentManager/Models/Role.cs
    startLine: 12
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Models
  syntax:
    content: >-
      [Required]

      public string RoleName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <Required>

      Public Property RoleName As String
  overload: EnvironmentManager.Models.Role.RoleName*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
- uid: EnvironmentManager.Models.Role.Description
  commentId: P:EnvironmentManager.Models.Role.Description
  id: Description
  parent: EnvironmentManager.Models.Role
  langs:
  - csharp
  - vb
  name: Description
  nameWithType: Role.Description
  fullName: EnvironmentManager.Models.Role.Description
  type: Property
  source:
    remote:
      path: EnvironmentManager/Models/Role.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: Description
    path: EnvironmentManager/Models/Role.cs
    startLine: 15
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Models
  syntax:
    content: public string Description { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Description As String
  overload: EnvironmentManager.Models.Role.Description*
- uid: EnvironmentManager.Models.Role.CreatedDate
  commentId: P:EnvironmentManager.Models.Role.CreatedDate
  id: CreatedDate
  parent: EnvironmentManager.Models.Role
  langs:
  - csharp
  - vb
  name: CreatedDate
  nameWithType: Role.CreatedDate
  fullName: EnvironmentManager.Models.Role.CreatedDate
  type: Property
  source:
    remote:
      path: EnvironmentManager/Models/Role.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: CreatedDate
    path: EnvironmentManager/Models/Role.cs
    startLine: 17
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Models
  syntax:
    content: public DateTime CreatedDate { get; set; }
    parameters: []
    return:
      type: System.DateTime
    content.vb: Public Property CreatedDate As Date
  overload: EnvironmentManager.Models.Role.CreatedDate*
- uid: EnvironmentManager.Models.Role.LastModifiedDate
  commentId: P:EnvironmentManager.Models.Role.LastModifiedDate
  id: LastModifiedDate
  parent: EnvironmentManager.Models.Role
  langs:
  - csharp
  - vb
  name: LastModifiedDate
  nameWithType: Role.LastModifiedDate
  fullName: EnvironmentManager.Models.Role.LastModifiedDate
  type: Property
  source:
    remote:
      path: EnvironmentManager/Models/Role.cs
      branch: fix/docUpdate
      repo: https://github.com/40626785/SEGroup.git
    id: LastModifiedDate
    path: EnvironmentManager/Models/Role.cs
    startLine: 19
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Models
  syntax:
    content: public DateTime LastModifiedDate { get; set; }
    parameters: []
    return:
      type: System.DateTime
    content.vb: Public Property LastModifiedDate As Date
  overload: EnvironmentManager.Models.Role.LastModifiedDate*
references:
- uid: EnvironmentManager.Models
  commentId: N:EnvironmentManager.Models
  href: EnvironmentManager.html
  name: EnvironmentManager.Models
  nameWithType: EnvironmentManager.Models
  fullName: EnvironmentManager.Models
  spec.csharp:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Models
    name: Models
    href: EnvironmentManager.Models.html
  spec.vb:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Models
    name: Models
    href: EnvironmentManager.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: EnvironmentManager.Models.Role.RoleId*
  commentId: Overload:EnvironmentManager.Models.Role.RoleId
  href: EnvironmentManager.Models.Role.html#EnvironmentManager_Models_Role_RoleId
  name: RoleId
  nameWithType: Role.RoleId
  fullName: EnvironmentManager.Models.Role.RoleId
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: EnvironmentManager.Models.Role.RoleName*
  commentId: Overload:EnvironmentManager.Models.Role.RoleName
  href: EnvironmentManager.Models.Role.html#EnvironmentManager_Models_Role_RoleName
  name: RoleName
  nameWithType: Role.RoleName
  fullName: EnvironmentManager.Models.Role.RoleName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: EnvironmentManager.Models.Role.Description*
  commentId: Overload:EnvironmentManager.Models.Role.Description
  href: EnvironmentManager.Models.Role.html#EnvironmentManager_Models_Role_Description
  name: Description
  nameWithType: Role.Description
  fullName: EnvironmentManager.Models.Role.Description
- uid: EnvironmentManager.Models.Role.CreatedDate*
  commentId: Overload:EnvironmentManager.Models.Role.CreatedDate
  href: EnvironmentManager.Models.Role.html#EnvironmentManager_Models_Role_CreatedDate
  name: CreatedDate
  nameWithType: Role.CreatedDate
  fullName: EnvironmentManager.Models.Role.CreatedDate
- uid: System.DateTime
  commentId: T:System.DateTime
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.datetime
  name: DateTime
  nameWithType: DateTime
  fullName: System.DateTime
  nameWithType.vb: Date
  fullName.vb: Date
  name.vb: Date
- uid: EnvironmentManager.Models.Role.LastModifiedDate*
  commentId: Overload:EnvironmentManager.Models.Role.LastModifiedDate
  href: EnvironmentManager.Models.Role.html#EnvironmentManager_Models_Role_LastModifiedDate
  name: LastModifiedDate
  nameWithType: Role.LastModifiedDate
  fullName: EnvironmentManager.Models.Role.LastModifiedDate
