### YamlMime:ManagedReference
items:
- uid: EnvironmentManager.Models.Maintenance
  commentId: T:EnvironmentManager.Models.Maintenance
  id: Maintenance
  parent: EnvironmentManager.Models
  children:
  - EnvironmentManager.Models.Maintenance.Description
  - EnvironmentManager.Models.Maintenance.DueDate
  - EnvironmentManager.Models.Maintenance.Id
  - EnvironmentManager.Models.Maintenance.Overdue
  - EnvironmentManager.Models.Maintenance.Priority
  langs:
  - csharp
  - vb
  name: Maintenance
  nameWithType: Maintenance
  fullName: EnvironmentManager.Models.Maintenance
  type: Class
  source:
    remote:
      path: EnvironmentManager/Models/Maintenance.cs
      branch: html-generation-for-sensor
      repo: https://github.com/40626785/Environment-Manager.git
    id: Maintenance
    path: EnvironmentManager/Models/Maintenance.cs
    startLine: 6
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Models
  syntax:
    content: >-
      [Table("maintenance")]

      [PrimaryKey("Id", new string[] { })]

      public class Maintenance
    content.vb: >-
      <Table("maintenance")>

      <PrimaryKey("Id", New String() { })>

      Public Class Maintenance
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.ComponentModel.DataAnnotations.Schema.TableAttribute
    ctor: System.ComponentModel.DataAnnotations.Schema.TableAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: maintenance
- uid: EnvironmentManager.Models.Maintenance.Id
  commentId: P:EnvironmentManager.Models.Maintenance.Id
  id: Id
  parent: EnvironmentManager.Models.Maintenance
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: Maintenance.Id
  fullName: EnvironmentManager.Models.Maintenance.Id
  type: Property
  source:
    remote:
      path: EnvironmentManager/Models/Maintenance.cs
      branch: html-generation-for-sensor
      repo: https://github.com/40626785/Environment-Manager.git
    id: Id
    path: EnvironmentManager/Models/Maintenance.cs
    startLine: 10
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Models
  syntax:
    content: public int Id { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Id As Integer
  overload: EnvironmentManager.Models.Maintenance.Id*
- uid: EnvironmentManager.Models.Maintenance.DueDate
  commentId: P:EnvironmentManager.Models.Maintenance.DueDate
  id: DueDate
  parent: EnvironmentManager.Models.Maintenance
  langs:
  - csharp
  - vb
  name: DueDate
  nameWithType: Maintenance.DueDate
  fullName: EnvironmentManager.Models.Maintenance.DueDate
  type: Property
  source:
    remote:
      path: EnvironmentManager/Models/Maintenance.cs
      branch: html-generation-for-sensor
      repo: https://github.com/40626785/Environment-Manager.git
    id: DueDate
    path: EnvironmentManager/Models/Maintenance.cs
    startLine: 13
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Models
  syntax:
    content: >-
      [Required]

      public DateTime DueDate { get; set; }
    parameters: []
    return:
      type: System.DateTime
    content.vb: >-
      <Required>

      Public Property DueDate As Date
  overload: EnvironmentManager.Models.Maintenance.DueDate*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
- uid: EnvironmentManager.Models.Maintenance.Overdue
  commentId: P:EnvironmentManager.Models.Maintenance.Overdue
  id: Overdue
  parent: EnvironmentManager.Models.Maintenance
  langs:
  - csharp
  - vb
  name: Overdue
  nameWithType: Maintenance.Overdue
  fullName: EnvironmentManager.Models.Maintenance.Overdue
  type: Property
  source:
    remote:
      path: EnvironmentManager/Models/Maintenance.cs
      branch: html-generation-for-sensor
      repo: https://github.com/40626785/Environment-Manager.git
    id: Overdue
    path: EnvironmentManager/Models/Maintenance.cs
    startLine: 15
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Models
  syntax:
    content: >-
      [Required]

      public bool Overdue { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: >-
      <Required>

      Public Property Overdue As Boolean
  overload: EnvironmentManager.Models.Maintenance.Overdue*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
- uid: EnvironmentManager.Models.Maintenance.Priority
  commentId: P:EnvironmentManager.Models.Maintenance.Priority
  id: Priority
  parent: EnvironmentManager.Models.Maintenance
  langs:
  - csharp
  - vb
  name: Priority
  nameWithType: Maintenance.Priority
  fullName: EnvironmentManager.Models.Maintenance.Priority
  type: Property
  source:
    remote:
      path: EnvironmentManager/Models/Maintenance.cs
      branch: html-generation-for-sensor
      repo: https://github.com/40626785/Environment-Manager.git
    id: Priority
    path: EnvironmentManager/Models/Maintenance.cs
    startLine: 17
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Models
  syntax:
    content: >-
      [Required]

      public int Priority { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: >-
      <Required>

      Public Property Priority As Integer
  overload: EnvironmentManager.Models.Maintenance.Priority*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
- uid: EnvironmentManager.Models.Maintenance.Description
  commentId: P:EnvironmentManager.Models.Maintenance.Description
  id: Description
  parent: EnvironmentManager.Models.Maintenance
  langs:
  - csharp
  - vb
  name: Description
  nameWithType: Maintenance.Description
  fullName: EnvironmentManager.Models.Maintenance.Description
  type: Property
  source:
    remote:
      path: EnvironmentManager/Models/Maintenance.cs
      branch: html-generation-for-sensor
      repo: https://github.com/40626785/Environment-Manager.git
    id: Description
    path: EnvironmentManager/Models/Maintenance.cs
    startLine: 19
  assemblies:
  - EnvironmentManager
  namespace: EnvironmentManager.Models
  syntax:
    content: >-
      [Required]

      public string Description { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <Required>

      Public Property Description As String
  overload: EnvironmentManager.Models.Maintenance.Description*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
references:
- uid: EnvironmentManager.Models
  commentId: N:EnvironmentManager.Models
  href: EnvironmentManager.html
  name: EnvironmentManager.Models
  nameWithType: EnvironmentManager.Models
  fullName: EnvironmentManager.Models
  spec.csharp:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Models
    name: Models
    href: EnvironmentManager.Models.html
  spec.vb:
  - uid: EnvironmentManager
    name: EnvironmentManager
    href: EnvironmentManager.html
  - name: .
  - uid: EnvironmentManager.Models
    name: Models
    href: EnvironmentManager.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: EnvironmentManager.Models.Maintenance.Id*
  commentId: Overload:EnvironmentManager.Models.Maintenance.Id
  href: EnvironmentManager.Models.Maintenance.html#EnvironmentManager_Models_Maintenance_Id
  name: Id
  nameWithType: Maintenance.Id
  fullName: EnvironmentManager.Models.Maintenance.Id
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: EnvironmentManager.Models.Maintenance.DueDate*
  commentId: Overload:EnvironmentManager.Models.Maintenance.DueDate
  href: EnvironmentManager.Models.Maintenance.html#EnvironmentManager_Models_Maintenance_DueDate
  name: DueDate
  nameWithType: Maintenance.DueDate
  fullName: EnvironmentManager.Models.Maintenance.DueDate
- uid: System.DateTime
  commentId: T:System.DateTime
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.datetime
  name: DateTime
  nameWithType: DateTime
  fullName: System.DateTime
  nameWithType.vb: Date
  fullName.vb: Date
  name.vb: Date
- uid: EnvironmentManager.Models.Maintenance.Overdue*
  commentId: Overload:EnvironmentManager.Models.Maintenance.Overdue
  href: EnvironmentManager.Models.Maintenance.html#EnvironmentManager_Models_Maintenance_Overdue
  name: Overdue
  nameWithType: Maintenance.Overdue
  fullName: EnvironmentManager.Models.Maintenance.Overdue
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: EnvironmentManager.Models.Maintenance.Priority*
  commentId: Overload:EnvironmentManager.Models.Maintenance.Priority
  href: EnvironmentManager.Models.Maintenance.html#EnvironmentManager_Models_Maintenance_Priority
  name: Priority
  nameWithType: Maintenance.Priority
  fullName: EnvironmentManager.Models.Maintenance.Priority
- uid: EnvironmentManager.Models.Maintenance.Description*
  commentId: Overload:EnvironmentManager.Models.Maintenance.Description
  href: EnvironmentManager.Models.Maintenance.html#EnvironmentManager_Models_Maintenance_Description
  name: Description
  nameWithType: Maintenance.Description
  fullName: EnvironmentManager.Models.Maintenance.Description
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
